In [1]:
import pandas as pd

In [2]:
results = pd.read_csv('results.csv')

In [3]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [4]:
races = pd.read_csv('races.csv')

In [5]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [6]:
drivers = pd.read_csv('drivers.csv')

In [7]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [8]:
merged = results.merge(drivers, on='driverId')

In [9]:
merged.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fastestLapSpeed,statusId,driverRef,number_y,code,forename,surname,dob,nationality,url
0,1,18,1,1,22,1,1,1,1,10.0,...,218.300,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,...,217.586,1,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,...,216.719,1,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,...,215.464,1,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,18,5,1,23,3,5,5,5,4.0,...,218.385,1,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [10]:
merged['driver_name'] = merged['forename'] + ' ' + merged['surname']

In [11]:
constructors = pd.read_csv('constructors.csv')

In [12]:
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [13]:
merged = merged.merge(
    constructors,
    on='constructorId',
    how='left'
)

In [14]:
merged.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,forename,surname,dob,nationality_x,url_x,driver_name,constructorRef,name,nationality_y,url_y
0,1,18,1,1,22,1,1,1,1,10.0,...,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis Hamilton,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,18,2,2,3,5,2,2,2,8.0,...,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick Heidfeld,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,18,3,3,7,7,3,3,3,6.0,...,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico Rosberg,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,18,4,4,5,11,4,4,4,5.0,...,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando Alonso,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,18,5,1,23,3,5,5,5,4.0,...,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki Kovalainen,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren

In [15]:
races = pd.read_csv('races.csv')

In [16]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [17]:
merged = merged.merge(
    races[['raceId','year','round','circuitId','name']],
    on='raceId',
    how='left'
)

In [18]:
merged.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,url_x,driver_name,constructorRef,name_x,nationality_y,url_y,year,round,circuitId,name_y
0,1,18,1,1,22,1,1,1,1,10.0,...,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis Hamilton,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix
1,2,18,2,2,3,5,2,2,2,8.0,...,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick Heidfeld,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber,2008,1,1,Australian Grand Prix
2,3,18,3,3,7,7,3,3,3,6.0,...,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico Rosberg,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,2008,1,1,Australian Grand Prix
3,4,18,4,4,5,11,4,4,4,5.0,...,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando Alonso,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...,2008,1,1,Australian Grand Prix
4,5,18,5,1,23,3,5,5,5,4.0,...,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki Kovalainen,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix

In [19]:
status = pd.read_csv('status.csv')

In [20]:
status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [21]:
merged = merged.merge(
    status,
    on='statusId',
    how='left'
)

In [22]:
merged.to_csv('master_results.csv', index=False)

In [23]:
merged.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number_x', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'number_y', 'code',
       'forename', 'surname', 'dob', 'nationality_x', 'url_x', 'driver_name',
       'constructorRef', 'name_x', 'nationality_y', 'url_y', 'year', 'round',
       'circuitId', 'name_y', 'status'],
      dtype='object')

In [24]:
driver_points = merged.groupby('driver_name')['points'].sum().sort_values(ascending=False)

driver_points.head(20)

driver_name
Lewis Hamilton        4820.5
Sebastian Vettel      3098.0
Max Verstappen        2912.5
Fernando Alonso       2329.0
Kimi Räikkönen        1873.0
Valtteri Bottas       1788.0
Nico Rosberg          1594.5
Sergio Pérez          1585.0
Michael Schumacher    1566.0
Charles Leclerc       1363.0
Daniel Ricciardo      1320.0
Jenson Button         1235.0
Carlos Sainz          1203.5
Felipe Massa          1167.0
Mark Webber           1047.5
Lando Norris           950.0
Alain Prost            798.5
George Russell         664.0
Rubens Barrichello     658.0
Ayrton Senna           614.0
Name: points, dtype: float64

In [25]:
top_drivers = (
    merged.groupby('driver_name')
    .agg(
        Total_Points=('points','sum'),
        Races=('raceId','count'),
        Wins=('positionOrder', lambda x: (x==1).sum())
    )
    .sort_values('Total_Points', ascending=False)
)

top_drivers.head(20)

                    Total_Points  Races  Wins
driver_name
Lewis Hamilton            4820.5    356   105
Sebastian Vettel          3098.0    300    53
Max Verstappen            2912.5    209    63
Fernando Alonso           2329.0    404    32
Kimi Räikkönen            1873.0    352    21
Valtteri Bottas           1788.0    247    10
Nico Rosberg              1594.5    206    23
Sergio Pérez              1585.0    283     6
Michael Schumacher        1566.0    308    91
Charles Leclerc           1363.0    149     8
Daniel Ricciardo          1320.0    257     8
Jenson Button             1235.0    309    15
Carlos Sainz              1203.5    208     4
Felipe Massa              1167.0    271    11
Mark Webber               1047.5    217     9
Lando Norris               950.0    128     4
Alain Prost                798.5    202    51
George Russell             664.0    128     3
Rubens Barrichello         658.0    326    11
Ayrton Senna               614.0    162    41

In [26]:
driver_standings = pd.read_csv('driver_standings.csv')

In [27]:
driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [28]:
driver_standings = pd.read_csv('driver_standings.csv')

In [29]:
driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [30]:
driver_standings.shape

(34863, 7)

In [31]:
driver_standings['raceId'].nunique()

1125

In [32]:
driver_standings['driverId'].nunique()

854

In [33]:
constructors_standings = pd.read_csv('constructor_standings.csv')

In [34]:
constructors_standings.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0

In [35]:
# DRIVER ALPHA FRAMEWORK

# 1. Opportunity Utilization Score
# 2. Teammate Dominance Score
# 3. Car Outperformance Score
# 4. Championship Conversion Score
# 5. Era Adjustment Score

In [36]:
driver_summary = (
    merged.groupby('driver_name')
    .agg(
        Races=('raceId', 'count'),
        Wins=('positionOrder', lambda x: (x == 1).sum()),
        Podiums=('positionOrder', lambda x: (x <= 3).sum()),
        Total_Points=('points', 'sum')
    )
)

driver_summary.head()

               Races  Wins  Podiums  Total_Points
driver_name
Adolf Brudes       1     0        0           0.0
Adolfo Cruz        1     0        0           0.0
Adrian Sutil     128     0        0         124.0
Adrián Campos     21     0        0           0.0
Aguri Suzuki      88     0        1           8.0

In [37]:
driver_summary['Win_Rate'] = driver_summary['Wins'] / driver_summary['Races']
driver_summary['Podium_Rate'] = driver_summary['Podiums'] / driver_summary['Races']

driver_summary.head()

               Races  Wins  Podiums  Total_Points  Win_Rate  Podium_Rate
driver_name
Adolf Brudes       1     0        0           0.0       0.0     0.000000
Adolfo Cruz        1     0        0           0.0       0.0     0.000000
Adrian Sutil     128     0        0         124.0       0.0     0.000000
Adrián Campos     21     0        0           0.0       0.0     0.000000
Aguri Suzuki      88     0        1           8.0       0.0     0.011364

In [38]:
driver_summary.sort_values(
    'Win_Rate',
    ascending=False
).head(20)

                    Races  Wins  Podiums  Total_Points  Win_Rate  Podium_Rate
driver_name
Lee Wallard             2     1        1          9.00  0.500000     0.500000
Juan Fangio            58    24       35        279.14  0.413793     0.603448
Bill Vukovich           5     2        2         19.00  0.400000     0.400000
Alberto Ascari         36    13       17        140.00  0.361111     0.472222
Jim Clark              73    25       32        274.00  0.342466     0.438356
Max Verstappen        209    63      112       2912.50  0.301435     0.535885
Michael Schumacher    308    91      155       1566.00  0.295455     0.503247
Lewis Hamilton        356   105      202       4820.50  0.294944     0.567416
Jackie Stewart        100    27       43        360.00  0.270000     0.430000
Ayrton Senna          162    41       80        614.00  0.253086     0.493827
Alain Prost           202    51      106        798.50  0.252475     0.524752
Stirling Moss          73    16       24        186.50  0.219178     0.328767
Bob Sweikert            5     1        1          8.00  0.200000     0.200000
Damon Hill            122    22       42        360.00  0.180328     0.344262
Sebastian Vettel      300    53      122       3098.00  0.176667     0.406667
Pat Flaherty            6     1        1          8.00  0.166667     0.166667
Nigel Mansell         192    31       59        482.00  0.161458     0.307292
Tony Brooks            41     6       10         75.00  0.146341     0.243902
Niki Lauda            174    25       54        420.50  0.143678     0.310345
Nino Farina            37     5       20        127.33  0.135135     0.540541

In [39]:
qualified_drivers = driver_summary[
    driver_summary['Races'] >= 50
]

qualified_drivers.sort_values(
    'Win_Rate',
    ascending=False
).head(20)

                    Races  Wins  Podiums  Total_Points  Win_Rate  Podium_Rate
driver_name
Juan Fangio            58    24       35        279.14  0.413793     0.603448
Jim Clark              73    25       32        274.00  0.342466     0.438356
Max Verstappen        209    63      112       2912.50  0.301435     0.535885
Michael Schumacher    308    91      155       1566.00  0.295455     0.503247
Lewis Hamilton        356   105      202       4820.50  0.294944     0.567416
Jackie Stewart        100    27       43        360.00  0.270000     0.430000
Ayrton Senna          162    41       80        614.00  0.253086     0.493827
Alain Prost           202    51      106        798.50  0.252475     0.524752
Stirling Moss          73    16       24        186.50  0.219178     0.328767
Damon Hill            122    22       42        360.00  0.180328     0.344262
Sebastian Vettel      300    53      122       3098.00  0.176667     0.406667
Nigel Mansell         192    31       59        482.00  0.161458     0.307292
Niki Lauda            174    25       54        420.50  0.143678     0.310345
Mika Häkkinen         165    20       51        420.00  0.121212     0.309091
Nico Rosberg          206    23       57       1594.50  0.111650     0.276699
Nelson Piquet         207    23       60        485.50  0.111111     0.289855
Jack Brabham          129    14       31        261.00  0.108527     0.240310
James Hunt             93    10       23        179.00  0.107527     0.247312
Alan Jones            117    12       24        206.00  0.102564     0.205128
Jochen Rindt           62     6       13        109.00  0.096774     0.209677

In [40]:
driver_summary['Opportunity_Score'] = (
    driver_summary['Win_Rate'] * 70 +
    driver_summary['Podium_Rate'] * 30
)

qualified_drivers = driver_summary[
    driver_summary['Races'] >= 50
]

qualified_drivers.sort_values(
    'Opportunity_Score',
    ascending=False
).head(20)

,Races,Wins,Podiums,Total_Points,Win_Rate,Podium_Rate,Opportunity_Score
driver_name,,,,,,,
Juan Fangio,58,24,35,279.14,0.413793,0.603448,47.068966
Lewis Hamilton,356,105,202,4820.50,0.294944,0.567416,37.668539
Max Verstappen,209,63,112,2912.50,0.301435,0.535885,37.177033
Jim Clark,73,25,32,274.00,0.342466,0.438356,37.123288
Michael Schumacher,308,91,155,1566.00,0.295455,0.503247,35.779221
Alain Prost,202,51,106,798.50,0.252475,0.524752,33.415842
Ayrton Senna,162,41,80,614.00,0.253086,0.493827,32.530864
Jackie Stewart,100,27,43,360.00,0.270000,0.430000,31.800000
Stirling Moss,73,16,24,186.50,0.219178,0.328767,25.205479
Sebastian Vettel,300,53,122,3098.00,0.176667,0.406667,24.566667
Damon Hill,122,22,42,360.00,0.180328,0.344262,22.950820
Nigel Mansell,192,31,59,482.00,0.161458,0.307292,20.520833
Niki Lauda,174,25,54,420.50,0.143678,0.310345,19.367816
Mika Häkkinen,165,20,51,420.00,0.121212,0.309091,17.757576
Nelson Piquet,207,23,60,485.50,0.111111,0.289855,16.473430
Nico Rosberg,206,23,57,1594.50,0.111650,0.276699,16.116505
Carlos Reutemann,146,12,45,310.00,0.082192,0.308219,15.000000
Jody Scheckter,113,10,33,255.00,0.088496,0.292035,14.955752
James Hunt,93,10,23,179.00,0.107527,0.247312,14.946237
Jack Brabham,129,14,31,261.00,0.108527,0.240310,14.806202

In [41]:
# CHECKPOINT 1 COMPLETE

# Completed:
# - Master Results Table
# - Driver Summary Table
# - Win Rate
# - Podium Rate
# - Opportunity Utilization Framework
# - 50 Race Eligibility Rule

# Next Session:
# 1. Build Opportunity Score v1
# 2. Create Teammate Dominance Score
# 3. Design Car Outperformance Metric
# 4. Start Driver Alpha Formula

In [42]:
driver_summary['Opportunity_Score'] = (
    driver_summary['Win_Rate'] * 70 +
    driver_summary['Podium_Rate'] * 30
)

qualified_drivers = driver_summary[
    driver_summary['Races'] >= 50
]

qualified_drivers.sort_values(
    'Opportunity_Score',
    ascending=False
).head(20)

,Races,Wins,Podiums,Total_Points,Win_Rate,Podium_Rate,Opportunity_Score
driver_name,,,,,,,
Juan Fangio,58,24,35,279.14,0.413793,0.603448,47.068966
Lewis Hamilton,356,105,202,4820.50,0.294944,0.567416,37.668539
Max Verstappen,209,63,112,2912.50,0.301435,0.535885,37.177033
Jim Clark,73,25,32,274.00,0.342466,0.438356,37.123288
Michael Schumacher,308,91,155,1566.00,0.295455,0.503247,35.779221
Alain Prost,202,51,106,798.50,0.252475,0.524752,33.415842
Ayrton Senna,162,41,80,614.00,0.253086,0.493827,32.530864
Jackie Stewart,100,27,43,360.00,0.270000,0.430000,31.800000
Stirling Moss,73,16,24,186.50,0.219178,0.328767,25.205479
Sebastian Vettel,300,53,122,3098.00,0.176667,0.406667,24.566667
Damon Hill,122,22,42,360.00,0.180328,0.344262,22.950820
Nigel Mansell,192,31,59,482.00,0.161458,0.307292,20.520833
Niki Lauda,174,25,54,420.50,0.143678,0.310345,19.367816
Mika Häkkinen,165,20,51,420.00,0.121212,0.309091,17.757576
Nelson Piquet,207,23,60,485.50,0.111111,0.289855,16.473430
Nico Rosberg,206,23,57,1594.50,0.111650,0.276699,16.116505
Carlos Reutemann,146,12,45,310.00,0.082192,0.308219,15.000000
Jody Scheckter,113,10,33,255.00,0.088496,0.292035,14.955752
James Hunt,93,10,23,179.00,0.107527,0.247312,14.946237
Jack Brabham,129,14,31,261.00,0.108527,0.240310,14.806202

In [43]:
merged[['driver_name','constructorRef','year']].head(20)

           driver_name constructorRef  year
0       Lewis Hamilton        mclaren  2008
1        Nick Heidfeld     bmw_sauber  2008
2         Nico Rosberg       williams  2008
3      Fernando Alonso        renault  2008
4    Heikki Kovalainen        mclaren  2008
5      Kazuki Nakajima       williams  2008
6   Sébastien Bourdais     toro_rosso  2008
7       Kimi Räikkönen        ferrari  2008
8        Robert Kubica     bmw_sauber  2008
9           Timo Glock         toyota  2008
10         Takuma Sato    super_aguri  2008
11   Nelson Piquet Jr.        renault  2008
12        Felipe Massa        ferrari  2008
13     David Coulthard       red_bull  2008
14        Jarno Trulli         toyota  2008
15        Adrian Sutil    force_india  2008
16         Mark Webber       red_bull  2008
17       Jenson Button          honda  2008
18    Anthony Davidson    super_aguri  2008
19    Sebastian Vettel     toro_rosso  2008

In [44]:
team_drivers = (
    merged.groupby(['year','constructorRef'])['driver_name']
    .nunique()
    .reset_index(name='drivers')
)

team_drivers.sort_values('drivers', ascending=False).head(20)

     year constructorRef  drivers
83   1953   kurtis_kraft       29
101  1954   kurtis_kraft       27
142  1956       maserati       26
255  1962   lotus-climax       24
139  1956   kurtis_kraft       24
120  1955   kurtis_kraft       23
170  1958       maserati       23
236  1961   lotus-climax       23
153  1957   kurtis_kraft       22
207  1960  cooper-climax       22
62   1952   kurtis_kraft       21
104  1954       maserati       20
181  1959  cooper-climax       19
13   1950       maserati       18
123  1955       maserati       18
33   1951   kurtis_kraft       17
227  1961  cooper-climax       17
163  1958         cooper       17
58   1952        ferrari       16
156  1957       maserati       16

In [45]:
team_drivers['drivers'].describe()

count    1111.000000
mean        3.198020
std         3.227756
min         1.000000
25%         2.000000
50%         2.000000
75%         3.000000
max        29.000000
Name: drivers, dtype: float64

In [46]:
teammate_data = (
    merged.groupby(['year','constructorRef','driver_name'])
    .agg(
        Races=('raceId','count'),
        Wins=('positionOrder', lambda x: (x == 1).sum()),
        Podiums=('positionOrder', lambda x: (x <= 3).sum()),
        Points=('points','sum')
    )
    .reset_index()
)

teammate_data.head()

   year constructorRef      driver_name  Races  Wins  Podiums  Points
0  1950          adams  Bayliss Levrett      1     0        0     0.0
1  1950          adams    Bill Cantrell      1     0        0     0.0
2  1950           alfa  Consalvo Sanesi      1     0        0     0.0
3  1950           alfa      Juan Fangio      7     3        3    27.0
4  1950           alfa    Luigi Fagioli      6     0        5    28.0

In [47]:
teammate_data.shape

(3553, 7)

In [48]:
teammate_data.sort_values(
    ['year','constructorRef']
).head(20)

    year constructorRef        driver_name  Races  Wins  Podiums  Points
0   1950          adams    Bayliss Levrett      1     0        0     0.0
1   1950          adams      Bill Cantrell      1     0        0     0.0
2   1950           alfa    Consalvo Sanesi      1     0        0     0.0
3   1950           alfa        Juan Fangio      7     3        3    27.0
4   1950           alfa      Luigi Fagioli      6     0        5    28.0
5   1950           alfa        Nino Farina      6     3        3    30.0
6   1950           alfa      Piero Taruffi      1     0        0     0.0
7   1950           alfa        Reg Parnell      1     0        1     4.0
8   1950           alta     Geoff Crossley      2     0        0     0.0
9   1950           alta          Joe Kelly      1     0        0     0.0
10  1950         cooper       Harry Schell      1     0        0     0.0
11  1950          deidt       Bill Holland      1     0        1     6.0
12  1950          deidt         Mauri Rose      1     0        1     4.0
13  1950          deidt  Tony Bettenhausen      1     0        0     0.0
14  1950            era         Bob Gerard      2     0        0     0.0
15  1950            era      Cuth Harrison      3     0        0     0.0
16  1950            era     Leslie Johnson      1     0        0     0.0
17  1950            era       Peter Walker      1     0        0     0.0
18  1950            era          Tony Rolt      1     0        0     0.0
19  1950          ewing       Jimmy Davies      1     0        0     0.0

In [49]:
teammate_data = teammate_data[
    teammate_data['Races'] >= 5
]

In [50]:
teammate_data.shape

(1740, 7)

In [51]:
team_totals = (
    teammate_data.groupby(['year','constructorRef'])['Points']
    .sum()
    .reset_index(name='Team_Points')
)

teammate_data = teammate_data.merge(
    team_totals,
    on=['year','constructorRef'],
    how='left'
)

teammate_data['Teammate_Dominance'] = (
    teammate_data['Points'] /
    teammate_data['Team_Points']
)

teammate_data.head()

,year,constructorRef,driver_name,Races,Wins,Podiums,Points,Team_Points,Teammate_Dominance
0,1950,alfa,Juan Fangio,7,3,3,27.0,85.0,0.317647
1,1950,alfa,Luigi Fagioli,6,0,5,28.0,85.0,0.329412
2,1950,alfa,Nino Farina,6,3,3,30.0,85.0,0.352941
3,1950,ferrari,Alberto Ascari,5,0,2,11.0,11.0,1.000000
4,1950,lago,Johnny Claes,6,0,0,0.0,16.0,0.000000

In [52]:
teammate_data.sort_values(
    'Teammate_Dominance',
    ascending=False
)[[
    'driver_name',
    'year',
    'constructorRef',
    'Points',
    'Team_Points',
    'Teammate_Dominance'
]].head(20)

,driver_name,year,constructorRef,Points,Team_Points,Teammate_Dominance
1008,Derek Warwick,1993,footwork,4.0,4.0,1.0
227,Richard Attwood,1965,lotus-brm,2.0,2.0,1.0
178,Innes Ireland,1963,brp,6.0,6.0,1.0
993,Christian Fittipaldi,1992,minardi,1.0,1.0,1.0
182,John Surtees,1963,ferrari,22.0,22.0,1.0
531,Emerson Fittipaldi,1978,fittipaldi,17.0,17.0,1.0
188,Carel Godin de Beaufort,1963,porsche,2.0,2.0,1.0
191,Jo Siffert,1964,brabham-brm,7.0,7.0,1.0
476,Tom Pryce,1976,shadow,10.0,10.0,1.0
989,Karl Wendlinger,1992,march,3.0,3.0,1.0
371,Emerson Fittipaldi,1972,team_lotus,61.0,61.0,1.0
528,Derek Daly,1978,ensign,1.0,1.0,1.0
984,Bertrand Gachot,1992,larrousse,1.0,1.0,1.0
983,Stefano Modena,1992,jordan,1.0,1.0,1.0
477,Alan Jones,1976,surtees,7.0,7.0,1.0
981,Michele Alboreto,1992,footwork,6.0,6.0,1.0
1515,Jules Bianchi,2014,marussia,2.0,2.0,1.0
212,Jo Siffert,1965,brabham-brm,5.0,5.0,1.0
975,Pierluigi Martini,1992,dallara,2.0,2.0,1.0
364,Chris Amon,1972,matra,12.0,12.0,1.0

In [53]:
teammate_data['Team_Points'].describe()

count    1740.000000
mean       64.347609
std       117.661672
min         0.000000
25%         5.000000
50%        23.000000
75%        69.000000
max       790.000000
Name: Team_Points, dtype: float64

In [54]:
teammate_filtered = teammate_data[
    (teammate_data['Team_Points'] >= 50) &
    (teammate_data['Races'] >= 5)
].copy()

teammate_filtered.shape

(599, 9)

In [55]:
teammate_filtered.sort_values(
    'Teammate_Dominance',
    ascending=False
)[[
    'driver_name',
    'year',
    'constructorRef',
    'Points',
    'Team_Points',
    'Teammate_Dominance'
]].head(30)

,driver_name,year,constructorRef,Points,Team_Points,Teammate_Dominance
520,Jody Scheckter,1977,wolf,55.0,55.0,1.000000
371,Emerson Fittipaldi,1972,team_lotus,61.0,61.0,1.000000
186,Jim Clark,1963,lotus-climax,73.0,74.0,0.986486
588,Nelson Piquet,1980,brabham,54.0,55.0,0.981818
788,Ayrton Senna,1986,team_lotus,55.0,58.0,0.948276
1569,Carlos Sainz,2016,toro_rosso,46.0,50.0,0.920000
1017,Ayrton Senna,1993,mclaren,73.0,80.0,0.912500
1589,Carlos Sainz,2017,toro_rosso,48.0,53.0,0.905660
1502,Nico Hülkenberg,2013,sauber,51.0,57.0,0.894737
1032,Michael Schumacher,1994,benetton,92.0,103.0,0.893204
814,Ayrton Senna,1987,team_lotus,57.0,64.0,0.890625
1677,Valtteri Bottas,2022,alfa,47.0,53.0,0.886792
1170,Heinz-Harald Frentzen,1999,jordan,54.0,61.0,0.885246
1057,Damon Hill,1994,williams,91.0,105.0,0.866667
679,Keke Rosberg,1982,williams,44.0,52.0,0.846154
749,Alain Prost,1985,mclaren,76.0,90.0,0.844444
228,Jim Clark,1965,lotus-climax,54.0,64.0,0.843750
1586,Nico Hülkenberg,2017,renault,43.0,51.0,0.843137
1092,Michael Schumacher,1996,ferrari,59.0,70.0,0.842857
154,Graham Hill,1962,brm,52.0,62.0,0.838710
1424,Robert Kubica,2010,renault,136.0,163.0,0.834356
261,Jim Clark,1967,lotus-ford,41.0,50.0,0.820000
617,Nelson Piquet,1981,brabham,50.0,61.0,0.819672
685,Nelson Piquet,1983,brabham,59.0,72.0,0.819444
1600,Fernando Alonso,2018,mclaren,50.0,62.0,0.806452
633,Alain Prost,1981,renault,43.0,54.0,0.796296
472,James Hunt,1976,mclaren,69.0,88.0,0.784091
1658,Pierre Gasly,2021,alphatauri,110.0,142.0,0.774648
1689,Lando Norris,2022,mclaren,116.0,150.0,0.773333
781,Alain Prost,1986,mclaren,74.0,96.0,0.770833

In [56]:
teammate_counts = (
    teammate_filtered.groupby(
        ['year','constructorRef']
    )['driver_name']
    .nunique()
    .reset_index(name='num_drivers')
)

teammate_counts['num_drivers'].describe()

count    267.000000
mean       2.243446
std        0.674944
min        1.000000
25%        2.000000
50%        2.000000
75%        2.000000
max        6.000000
Name: num_drivers, dtype: float64

In [57]:
teammate_compare = teammate_filtered.copy()

teammate_compare['Best_Teammate_Points'] = (
    teammate_compare.groupby(
        ['year','constructorRef']
    )['Points']
    .transform('max')
)

teammate_compare.head()

,year,constructorRef,driver_name,Races,Wins,Podiums,Points,Team_Points,Teammate_Dominance,Best_Teammate_Points
0,1950,alfa,Juan Fangio,7,3,3,27.0,85.0,0.317647,30.0
1,1950,alfa,Luigi Fagioli,6,0,5,28.0,85.0,0.329412,30.0
2,1950,alfa,Nino Farina,6,3,3,30.0,85.0,0.352941,30.0
8,1951,alfa,Juan Fangio,8,3,5,37.0,59.0,0.627119,37.0
9,1951,alfa,Nino Farina,8,1,4,22.0,59.0,0.372881,37.0

In [58]:
team_rankings = teammate_filtered.copy()

team_rankings['Point_Rank'] = (
    team_rankings.groupby(
        ['year','constructorRef']
    )['Points']
    .rank(
        method='dense',
        ascending=False
    )
)

team_rankings.sort_values(
    ['year','constructorRef','Points'],
    ascending=[True,True,False]
).head(20)

,year,constructorRef,driver_name,Races,Wins,Podiums,Points,Team_Points,Teammate_Dominance,Point_Rank
2,1950,alfa,Nino Farina,6,3,3,30.0,85.0,0.352941,1.0
1,1950,alfa,Luigi Fagioli,6,0,5,28.0,85.0,0.329412,2.0
0,1950,alfa,Juan Fangio,7,3,3,27.0,85.0,0.317647,3.0
8,1951,alfa,Juan Fangio,8,3,5,37.0,59.0,0.627119,1.0
9,1951,alfa,Nino Farina,8,1,4,22.0,59.0,0.372881,2.0
10,1951,ferrari,Alberto Ascari,8,2,4,28.0,83.0,0.337349,1.0
11,1951,ferrari,José Froilán González,5,1,5,27.0,83.0,0.325301,2.0
12,1951,ferrari,Luigi Villoresi,7,0,3,18.0,83.0,0.216867,3.0
13,1951,ferrari,Piero Taruffi,5,0,1,10.0,83.0,0.120482,4.0
20,1952,ferrari,Alberto Ascari,7,6,6,53.5,112.5,0.475556,1.0
21,1952,ferrari,Nino Farina,8,0,4,27.0,112.5,0.240000,2.0
22,1952,ferrari,Piero Taruffi,6,1,3,22.0,112.5,0.195556,3.0
23,1952,ferrari,Rudi Fischer,5,0,2,10.0,112.5,0.088889,4.0
30,1953,ferrari,Alberto Ascari,9,5,5,46.5,122.5,0.379592,1.0
34,1953,ferrari,Nino Farina,8,1,5,32.0,122.5,0.261224,2.0
33,1953,ferrari,Mike Hawthorn,8,1,3,27.0,122.5,0.220408,3.0
32,1953,ferrari,Luigi Villoresi,9,0,3,17.0,122.5,0.138776,4.0
31,1953,ferrari,Louis Rosier,7,0,0,0.0,122.5,0.000000,5.0
41,1953,maserati,Juan Fangio,10,1,4,29.5,61.5,0.479675,1.0
40,1953,maserati,José Froilán González,6,0,3,14.5,61.5,0.235772,2.0

In [59]:
team_rankings[['driver_name','year','constructorRef','Points','Point_Rank']].head(20)

              driver_name  year constructorRef  Points  Point_Rank
0             Juan Fangio  1950           alfa    27.0         3.0
1           Luigi Fagioli  1950           alfa    28.0         2.0
2             Nino Farina  1950           alfa    30.0         1.0
8             Juan Fangio  1951           alfa    37.0         1.0
9             Nino Farina  1951           alfa    22.0         2.0
10         Alberto Ascari  1951        ferrari    28.0         1.0
11  José Froilán González  1951        ferrari    27.0         2.0
12        Luigi Villoresi  1951        ferrari    18.0         3.0
13          Piero Taruffi  1951        ferrari    10.0         4.0
20         Alberto Ascari  1952        ferrari    53.5         1.0
21            Nino Farina  1952        ferrari    27.0         2.0
22          Piero Taruffi  1952        ferrari    22.0         3.0
23           Rudi Fischer  1952        ferrari    10.0         4.0
30         Alberto Ascari  1953        ferrari    46.5         1.0
31           Louis Rosier  1953        ferrari     0.0         5.0
32        Luigi Villoresi  1953        ferrari    17.0         4.0
33          Mike Hawthorn  1953        ferrari    27.0         3.0
34            Nino Farina  1953        ferrari    32.0         2.0
39         Felice Bonetto  1953       maserati     6.5         4.0
40  José Froilán González  1953       maserati    14.5         2.0

In [60]:
teammate_compare = team_rankings.copy()

second_driver = (
    teammate_compare[
        teammate_compare['Point_Rank'] == 2
    ][[
        'year',
        'constructorRef',
        'Points'
    ]]
    .rename(
        columns={
            'Points':'Second_Driver_Points'
        }
    )
)

teammate_compare = teammate_compare.merge(
    second_driver,
    on=['year','constructorRef'],
    how='left'
)

teammate_compare[
    [
        'driver_name',
        'year',
        'constructorRef',
        'Points',
        'Point_Rank',
        'Second_Driver_Points'
    ]
].head(20)

,driver_name,year,constructorRef,Points,Point_Rank,Second_Driver_Points
0,Juan Fangio,1950,alfa,27.0,3.0,28.0
1,Luigi Fagioli,1950,alfa,28.0,2.0,28.0
2,Nino Farina,1950,alfa,30.0,1.0,28.0
3,Juan Fangio,1951,alfa,37.0,1.0,22.0
4,Nino Farina,1951,alfa,22.0,2.0,22.0
5,Alberto Ascari,1951,ferrari,28.0,1.0,27.0
6,José Froilán González,1951,ferrari,27.0,2.0,27.0
7,Luigi Villoresi,1951,ferrari,18.0,3.0,27.0
8,Piero Taruffi,1951,ferrari,10.0,4.0,27.0
9,Alberto Ascari,1952,ferrari,53.5,1.0,27.0
10,Nino Farina,1952,ferrari,27.0,2.0,27.0
11,Piero Taruffi,1952,ferrari,22.0,3.0,27.0
12,Rudi Fischer,1952,ferrari,10.0,4.0,27.0
13,Alberto Ascari,1953,ferrari,46.5,1.0,32.0
14,Louis Rosier,1953,ferrari,0.0,5.0,32.0
15,Luigi Villoresi,1953,ferrari,17.0,4.0,32.0
16,Mike Hawthorn,1953,ferrari,27.0,3.0,32.0
17,Nino Farina,1953,ferrari,32.0,2.0,32.0
18,Felice Bonetto,1953,maserati,6.5,4.0,14.5
19,José Froilán González,1953,maserati,14.5,2.0,14.5

In [61]:
top_teammates = teammate_compare[
    teammate_compare['Point_Rank'] <= 2
].copy()

top_teammates.shape

(533, 11)

In [62]:
head_to_head = top_teammates.copy()

leader_points = (
    head_to_head[
        head_to_head['Point_Rank'] == 1
    ][[
        'year',
        'constructorRef',
        'Points'
    ]]
    .rename(columns={'Points':'Leader_Points'})
)

head_to_head = head_to_head.merge(
    leader_points,
    on=['year','constructorRef'],
    how='left'
)

head_to_head['Head_To_Head_Score'] = (
    head_to_head['Points'] /
    head_to_head['Leader_Points']
)

head_to_head[
    [
        'driver_name',
        'year',
        'constructorRef',
        'Points',
        'Point_Rank',
        'Leader_Points',
        'Head_To_Head_Score'
    ]
].head(20)

,driver_name,year,constructorRef,Points,Point_Rank,Leader_Points,Head_To_Head_Score
0,Luigi Fagioli,1950,alfa,28.00,2.0,30.00,0.933333
1,Nino Farina,1950,alfa,30.00,1.0,30.00,1.000000
2,Juan Fangio,1951,alfa,37.00,1.0,37.00,1.000000
3,Nino Farina,1951,alfa,22.00,2.0,37.00,0.594595
4,Alberto Ascari,1951,ferrari,28.00,1.0,28.00,1.000000
5,José Froilán González,1951,ferrari,27.00,2.0,28.00,0.964286
6,Alberto Ascari,1952,ferrari,53.50,1.0,53.50,1.000000
7,Nino Farina,1952,ferrari,27.00,2.0,53.50,0.504673
8,Alberto Ascari,1953,ferrari,46.50,1.0,46.50,1.000000
9,Nino Farina,1953,ferrari,32.00,2.0,46.50,0.688172
10,José Froilán González,1953,maserati,14.50,2.0,29.50,0.491525
11,Juan Fangio,1953,maserati,29.50,1.0,29.50,1.000000
12,José Froilán González,1954,ferrari,26.64,1.0,26.64,1.000000
13,Mike Hawthorn,1954,ferrari,24.64,2.0,26.64,0.924925
14,Juan Fangio,1954,mercedes,40.14,1.0,40.14,1.000000
15,Karl Kling,1954,mercedes,12.00,2.0,40.14,0.298954
16,Juan Fangio,1955,mercedes,41.00,1.0,41.00,1.000000
17,Stirling Moss,1955,mercedes,23.00,2.0,41.00,0.560976
18,Juan Fangio,1956,ferrari,34.50,1.0,34.50,1.000000
19,Peter Collins,1956,ferrari,25.00,2.0,34.50,0.724638

In [63]:
driver_alpha_teammate = (
    head_to_head.groupby('driver_name')
    .agg(
        Seasons=('year','count'),
        Avg_Teammate_Score=('Head_To_Head_Score','mean')
    )
)

driver_alpha_teammate[
    driver_alpha_teammate['Seasons'] >= 5
].sort_values(
    'Avg_Teammate_Score',
    ascending=False
).head(30)

                    Seasons  Avg_Teammate_Score
driver_name
Juan Fangio               6            1.000000
Alain Prost              12            0.999421
Charles Leclerc           6            0.995413
Fernando Alonso          18            0.995006
Nelson Piquet             6            0.993056
Lewis Hamilton           19            0.980684
Pierre Gasly              5            0.965830
Ayrton Senna              9            0.959553
Max Verstappen           10            0.958609
Jackie Stewart            6            0.953901
Nico Rosberg              7            0.939347
Sebastian Vettel         14            0.924822
Jenson Button             9            0.918892
Michael Schumacher       18            0.915692
Lando Norris              6            0.905704
Nigel Mansell             7            0.869212
Carlos Sainz             10            0.868235
Jarno Trulli              5            0.867043
Mika Häkkinen             5            0.863846
Nico Hülkenberg          10            0.860973
Carlos Reutemann          5            0.854695
Emerson Fittipaldi        5            0.853333
Daniel Ricciardo          9            0.850751
Graham Hill               7            0.848013
Kimi Räikkönen           16            0.846760
Jean Alesi                5            0.840603
Niki Lauda                8            0.835526
Valtteri Bottas           9            0.827300
Esteban Ocon              7            0.809987
Ralf Schumacher           5            0.792222

In [64]:
constructor_strength = (
    merged.groupby(['year','constructorRef'])
    .agg(
        Team_Points=('points','sum')
    )
    .reset_index()
)

constructor_strength.sort_values(
    'Team_Points',
    ascending=False
).head(20)

      year constructorRef  Team_Points
1099  2023       red_bull        790.0
1025  2016       mercedes        765.0
1055  2019       mercedes        739.0
1089  2022       red_bull        724.0
1015  2015       mercedes        703.0
1005  2014       mercedes        701.0
1035  2017       mercedes        668.0
1045  2018       mercedes        655.0
970   2011       red_bull        650.0
1105  2024        mclaren        609.0
1078  2021       mercedes        604.5
995   2013       red_bull        596.0
1103  2024        ferrari        595.0
1079  2021       red_bull        578.5
1066  2020       mercedes        573.0
1041  2018        ferrari        571.0
1108  2024       red_bull        537.0
1031  2017        ferrari        522.0
1085  2022        ferrari        519.0
1052  2019        ferrari        504.0

In [65]:
constructor_strength['Car_Strength_Score'] = (
    constructor_strength['Team_Points'] /
    constructor_strength['Team_Points'].max()
)

constructor_strength.sort_values(
    'Car_Strength_Score',
    ascending=False
).head(20)

      year constructorRef  Team_Points  Car_Strength_Score
1099  2023       red_bull        790.0            1.000000
1025  2016       mercedes        765.0            0.968354
1055  2019       mercedes        739.0            0.935443
1089  2022       red_bull        724.0            0.916456
1015  2015       mercedes        703.0            0.889873
1005  2014       mercedes        701.0            0.887342
1035  2017       mercedes        668.0            0.845570
1045  2018       mercedes        655.0            0.829114
970   2011       red_bull        650.0            0.822785
1105  2024        mclaren        609.0            0.770886
1078  2021       mercedes        604.5            0.765190
995   2013       red_bull        596.0            0.754430
1103  2024        ferrari        595.0            0.753165
1079  2021       red_bull        578.5            0.732278
1066  2020       mercedes        573.0            0.725316
1041  2018        ferrari        571.0            0.722785
1108  2024       red_bull        537.0            0.679747
1031  2017        ferrari        522.0            0.660759
1085  2022        ferrari        519.0            0.656962
1052  2019        ferrari        504.0            0.637975

In [66]:
constructor_strength['Car_Strength_Score'] = (
    constructor_strength['Team_Points'] /
    constructor_strength['Team_Points'].max()
)

constructor_strength.sort_values(
    'Car_Strength_Score',
    ascending=False
).head(20)

      year constructorRef  Team_Points  Car_Strength_Score
1099  2023       red_bull        790.0            1.000000
1025  2016       mercedes        765.0            0.968354
1055  2019       mercedes        739.0            0.935443
1089  2022       red_bull        724.0            0.916456
1015  2015       mercedes        703.0            0.889873
1005  2014       mercedes        701.0            0.887342
1035  2017       mercedes        668.0            0.845570
1045  2018       mercedes        655.0            0.829114
970   2011       red_bull        650.0            0.822785
1105  2024        mclaren        609.0            0.770886
1078  2021       mercedes        604.5            0.765190
995   2013       red_bull        596.0            0.754430
1103  2024        ferrari        595.0            0.753165
1079  2021       red_bull        578.5            0.732278
1066  2020       mercedes        573.0            0.725316
1041  2018        ferrari        571.0            0.722785
1108  2024       red_bull        537.0            0.679747
1031  2017        ferrari        522.0            0.660759
1085  2022        ferrari        519.0            0.656962
1052  2019        ferrari        504.0            0.637975

In [67]:
constructor_strength['Car_Strength_Score'].describe()

count    1111.000000
mean        0.060599
std         0.136231
min         0.000000
25%         0.000000
50%         0.008861
75%         0.059494
max         1.000000
Name: Car_Strength_Score, dtype: float64

In [68]:
qualifying = pd.read_csv("qualifying.csv")
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [69]:
qualifying.shape

(10494, 9)

In [70]:
qualifying.isnull().sum()

qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

In [71]:
qualifying[['raceId']].head()

   raceId
0      18
1      18
2      18
3      18
4      18

In [72]:
qualifying['raceId'].nunique()

494

In [73]:
qualifying_merge = qualifying.merge(
    races[['raceId','year']],
    on='raceId',
    how='left'
)

qualifying_merge[['year','position']].head()

   year  position
0  2008         1
1  2008         2
2  2008         3
3  2008         4
4  2008         5

In [74]:
qualifying_merge['year'].describe()

count    10494.000000
mean      2011.260911
std          8.588508
min       1994.000000
25%       2006.000000
50%       2012.000000
75%       2018.000000
max       2024.000000
Name: year, dtype: float64

In [75]:
head_to_head['Outperformance_Score'] = (
    head_to_head['Points'] /
    head_to_head['Second_Driver_Points']
)

head_to_head.sort_values(
    'Outperformance_Score',
    ascending=False
)[[
    'driver_name',
    'year',
    'constructorRef',
    'Points',
    'Second_Driver_Points',
    'Outperformance_Score'
]].head(30)

,driver_name,year,constructorRef,Points,Second_Driver_Points,Outperformance_Score
75,Emerson Fittipaldi,1972,team_lotus,61.0,0.0,inf
38,Jim Clark,1963,lotus-climax,73.0,1.0,73.000000
122,Nelson Piquet,1980,brabham,54.0,1.0,54.000000
161,Ayrton Senna,1986,team_lotus,55.0,3.0,18.333333
419,Carlos Sainz,2016,toro_rosso,46.0,4.0,11.500000
205,Ayrton Senna,1993,mclaren,73.0,7.0,10.428571
433,Carlos Sainz,2017,toro_rosso,48.0,5.0,9.600000
210,Michael Schumacher,1994,benetton,92.0,10.0,9.200000
382,Nico Hülkenberg,2013,sauber,51.0,6.0,8.500000
169,Ayrton Senna,1987,team_lotus,57.0,7.0,8.142857
496,Valtteri Bottas,2022,alfa,47.0,6.0,7.833333
242,Heinz-Harald Frentzen,1999,jordan,54.0,7.0,7.714286
213,Damon Hill,1994,williams,91.0,14.0,6.500000
140,Keke Rosberg,1982,williams,44.0,8.0,5.500000
153,Alain Prost,1985,mclaren,76.0,14.0,5.428571
46,Jim Clark,1965,lotus-climax,54.0,10.0,5.400000
432,Nico Hülkenberg,2017,renault,43.0,8.0,5.375000
224,Michael Schumacher,1996,ferrari,59.0,11.0,5.363636
34,Graham Hill,1962,brm,52.0,10.0,5.200000
337,Robert Kubica,2010,renault,136.0,27.0,5.037037
23,Juan Fangio,1957,maserati,46.0,10.0,4.600000
53,Jim Clark,1967,lotus-ford,41.0,9.0,4.555556
128,Nelson Piquet,1981,brabham,50.0,11.0,4.545455
141,Nelson Piquet,1983,brabham,59.0,13.0,4.538462
443,Fernando Alonso,2018,mclaren,50.0,12.0,4.166667
54,Graham Hill,1968,lotus-ford,48.0,12.0,4.000000
129,Alain Prost,1981,renault,43.0,11.0,3.909091
69,Jochen Rindt,1970,team_lotus,45.0,12.0,3.750000
462,Max Verstappen,2019,red_bull,278.0,76.0,3.657895
98,James Hunt,1976,mclaren,69.0,19.0,3.631579

In [76]:
career_outperformance = (
    head_to_head.groupby('driver_name')
    .agg(
        Seasons=('year','count'),
        Avg_Outperformance=('Outperformance_Score','mean')
    )
)

career_outperformance[
    career_outperformance['Seasons'] >= 5
].sort_values(
    'Avg_Outperformance',
    ascending=False
).head(30)

                    Seasons  Avg_Outperformance
driver_name
Emerson Fittipaldi        5                 inf
Nelson Piquet             6           11.237509
Ayrton Senna              9            5.013689
Carlos Sainz             10            3.016996
Nico Hülkenberg          10            2.474500
Juan Fangio               6            2.470652
Michael Schumacher       18            2.310356
Fernando Alonso          18            2.266861
Damon Hill                5            2.230351
Alain Prost              12            2.211138
Graham Hill               7            2.194995
Max Verstappen           10            2.034539
Jackie Stewart            6            1.997035
Pierre Gasly              5            1.904076
Valtteri Bottas           9            1.883237
Lando Norris              6            1.726215
Kimi Räikkönen           16            1.562003
Niki Lauda                8            1.531853
Jenson Button             9            1.507841
Carlos Reutemann          5            1.486083
Charles Leclerc           6            1.438905
Sebastian Vettel         14            1.391807
Jean Alesi                5            1.385253
Juan Pablo Montoya        6            1.336823
Lewis Hamilton           19            1.324451
Mika Häkkinen             5            1.317645
Nigel Mansell             7            1.305723
Nico Rosberg              7            1.293485
Sergio Pérez             13            1.261938
Daniel Ricciardo          9            1.259417

In [77]:
driver_standings = pd.read_csv('driver_standings.csv')

driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [78]:
driver_standings.shape

(34863, 7)

In [79]:
driver_standings['raceId'].nunique()

1125

In [80]:
driver_standings['driverId'].nunique()

854

In [81]:
season_finals = (
    races.groupby('year')['raceId']
    .max()
    .reset_index()
)

season_finals.head()

   year  raceId
0  1950     839
1  1951     832
2  1952     824
3  1953     816
4  1954     807

In [82]:
season_finals.tail()

    year  raceId
70  2020    1047
71  2021    1073
72  2022    1096
73  2023    1120
74  2024    1144

In [83]:
final_standings = driver_standings.merge(
    season_finals,
    on='raceId',
    how='inner'
)

final_standings.head()

,driverStandingsId,raceId,driverId,points,position,positionText,wins,year
0,355,35,1,98.0,1,1,5,2008
1,356,35,2,60.0,6,6,0,2008
2,357,35,3,17.0,13,13,0,2008
3,358,35,4,61.0,5,5,2,2008
4,359,35,5,53.0,7,7,1,2008

In [84]:
final_standings['position'] = pd.to_numeric(
    final_standings['position'],
    errors='coerce'
)

final_standings.sort_values(
    ['year','position']
).head(20)

,driverStandingsId,raceId,driverId,points,position,positionText,wins,year
2730,43539,839,642,30.0,1,1,3,1950
2723,43550,839,579,27.0,2,2,3,1950
2729,43540,839,786,24.0,3,3,0,1950
2727,43543,839,627,13.0,4,4,0,1950
2713,43560,839,647,11.0,5,5,0,1950
2704,43570,839,593,9.0,6,6,1,1950
2703,43571,839,701,6.0,7,7,0,1950
2721,43552,839,669,5.0,8,8,0,1950
2705,43568,839,687,4.0,9,9,0,1950
2717,43556,839,589,4.0,10,10,0,1950
2728,43541,839,686,4.0,11,11,0,1950
2702,43572,839,768,4.0,12,12,0,1950
2667,43609,839,802,3.0,13,13,0,1950
2734,43542,839,704,3.0,14,14,0,1950
2712,43561,839,793,3.0,15,15,0,1950
2709,43564,839,626,3.0,16,16,0,1950
2701,43573,839,770,3.0,17,17,0,1950
2732,43546,839,741,3.0,18,18,0,1950
2672,43603,839,697,2.0,19,19,0,1950
2736,43607,839,774,1.0,20,20,0,1950

In [85]:
champions = final_standings[
    final_standings['position'] == 1
]

champions[['year','driverId','points']].head()

     year  driverId  points
0    2008         1    98.0
22   2007         8   110.0
71   2006         4   134.0
94   2005         4   133.0
121  2004        30   148.0

In [86]:
championships = (
    champions.groupby('driverId')
    .size()
    .reset_index(name='Championships')
)

championships.sort_values(
    'Championships',
    ascending=False
).head(20)

    driverId  Championships
0          1              7
6         30              7
30       579              5
5         20              4
12       117              4
33       830              4
11       102              3
13       137              3
23       328              3
25       356              3
16       182              3
19       224              2
8         57              2
32       647              2
21       289              2
2          4              2
27       373              2
4         18              1
29       578              1
26       358              1

In [87]:
drivers.columns

Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
       'nationality', 'url'],
      dtype='object')

In [88]:
drivers['driver_name'] = (
    drivers['forename'] + ' ' + drivers['surname']
)

drivers[['driverId','driver_name']].head()

   driverId        driver_name
0         1     Lewis Hamilton
1         2      Nick Heidfeld
2         3       Nico Rosberg
3         4    Fernando Alonso
4         5  Heikki Kovalainen

In [89]:
championships_named = championships.merge(
    drivers[['driverId','driver_name']],
    on='driverId',
    how='left'
)

championships_named.sort_values(
    'Championships',
    ascending=False
).head(20)

    driverId  Championships         driver_name
0          1              7      Lewis Hamilton
6         30              7  Michael Schumacher
30       579              5         Juan Fangio
5         20              4    Sebastian Vettel
12       117              4         Alain Prost
33       830              4      Max Verstappen
11       102              3        Ayrton Senna
13       137              3       Nelson Piquet
23       328              3      Jackie Stewart
25       356              3        Jack Brabham
16       182              3          Niki Lauda
19       224              2  Emerson Fittipaldi
8         57              2       Mika Häkkinen
32       647              2      Alberto Ascari
21       289              2         Graham Hill
2          4              2     Fernando Alonso
27       373              2           Jim Clark
4         18              1       Jenson Button
29       578              1       Mike Hawthorn
26       358              1        Jochen Rindt

In [90]:
championships_named.sort_values(
    'Championships',
    ascending=False
).head(20)

    driverId  Championships         driver_name
0          1              7      Lewis Hamilton
6         30              7  Michael Schumacher
30       579              5         Juan Fangio
5         20              4    Sebastian Vettel
12       117              4         Alain Prost
33       830              4      Max Verstappen
11       102              3        Ayrton Senna
13       137              3       Nelson Piquet
23       328              3      Jackie Stewart
25       356              3        Jack Brabham
16       182              3          Niki Lauda
19       224              2  Emerson Fittipaldi
8         57              2       Mika Häkkinen
32       647              2      Alberto Ascari
21       289              2         Graham Hill
2          4              2     Fernando Alonso
27       373              2           Jim Clark
4         18              1       Jenson Button
29       578              1       Mike Hawthorn
26       358              1        Jochen Rindt

In [91]:
championships_named['Championship_Score'] = (
    championships_named['Championships'] /
    championships_named['Championships'].max()
)

championships_named.sort_values(
    'Championship_Score',
    ascending=False
).head(20)

    driverId  Championships         driver_name  Championship_Score
0          1              7      Lewis Hamilton            1.000000
6         30              7  Michael Schumacher            1.000000
30       579              5         Juan Fangio            0.714286
5         20              4    Sebastian Vettel            0.571429
12       117              4         Alain Prost            0.571429
33       830              4      Max Verstappen            0.571429
11       102              3        Ayrton Senna            0.428571
13       137              3       Nelson Piquet            0.428571
23       328              3      Jackie Stewart            0.428571
25       356              3        Jack Brabham            0.428571
16       182              3          Niki Lauda            0.428571
19       224              2  Emerson Fittipaldi            0.285714
8         57              2       Mika Häkkinen            0.285714
32       647              2      Alberto Ascari            0.285714
21       289              2         Graham Hill            0.285714
2          4              2     Fernando Alonso            0.285714
27       373              2           Jim Clark            0.285714
4         18              1       Jenson Button            0.142857
29       578              1       Mike Hawthorn            0.142857
26       358              1        Jochen Rindt            0.142857

In [92]:
driver_alpha = driver_summary.copy()

In [93]:
driver_alpha.columns

Index(['Races', 'Wins', 'Podiums', 'Total_Points', 'Win_Rate', 'Podium_Rate',
       'Opportunity_Score'],
      dtype='object')

In [94]:
driver_alpha = driver_alpha.reset_index()

driver_alpha.head()

,driver_name,Races,Wins,Podiums,Total_Points,Win_Rate,Podium_Rate,Opportunity_Score
0,Adolf Brudes,1,0,0,0.0,0.0,0.000000,0.000000
1,Adolfo Cruz,1,0,0,0.0,0.0,0.000000,0.000000
2,Adrian Sutil,128,0,0,124.0,0.0,0.000000,0.000000
3,Adrián Campos,21,0,0,0.0,0.0,0.000000,0.000000
4,Aguri Suzuki,88,0,1,8.0,0.0,0.011364,0.340909

In [95]:
driver_alpha = driver_alpha.merge(
    career_outperformance.reset_index(),
    on='driver_name',
    how='left'
)

driver_alpha = driver_alpha.merge(
    championships_named[
        ['driver_name','Championship_Score']
    ],
    on='driver_name',
    how='left'
)

driver_alpha.head()

,driver_name,Races,Wins,Podiums,Total_Points,Win_Rate,Podium_Rate,Opportunity_Score,Seasons,Avg_Outperformance,Championship_Score
0,Adolf Brudes,1,0,0,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN
1,Adolfo Cruz,1,0,0,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN
2,Adrian Sutil,128,0,0,124.0,0.0,0.000000,0.000000,3.0,1.597884,NaN
3,Adrián Campos,21,0,0,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN
4,Aguri Suzuki,88,0,1,8.0,0.0,0.011364,0.340909,NaN,NaN,NaN

In [96]:
driver_alpha = driver_alpha.fillna(0)

driver_alpha['Driver_Alpha_V1'] = (
    driver_alpha['Opportunity_Score'] * 0.4 +
    driver_alpha['Avg_Outperformance'] * 0.4 +
    driver_alpha['Championship_Score'] * 0.2
)

driver_alpha[
    driver_alpha['Races'] >= 50
].sort_values(
    'Driver_Alpha_V1',
    ascending=False
)[[
    'driver_name',
    'Races',
    'Opportunity_Score',
    'Avg_Outperformance',
    'Championship_Score',
    'Driver_Alpha_V1'
]].head(30)

,driver_name,Races,Opportunity_Score,Avg_Outperformance,Championship_Score,Driver_Alpha_V1
228,Emerson Fittipaldi,149,13.624161,inf,0.285714,inf
415,Jim Clark,73,37.123288,27.651852,0.285714,25.967199
474,Juan Fangio,58,47.068966,2.470652,0.714286,19.958704
571,Max Verstappen,209,37.177033,2.034539,0.571429,15.798915
523,Lewis Hamilton,356,37.668539,1.324451,1.000000,15.797196
578,Michael Schumacher,308,35.779221,2.310356,1.000000,15.435831
62,Ayrton Senna,162,32.530864,5.013689,0.428571,15.103535
8,Alain Prost,202,33.415842,2.211138,0.571429,14.365077
385,Jackie Stewart,100,31.800000,1.997035,0.428571,13.604528
608,Nelson Piquet,207,16.473430,11.237509,0.428571,11.170090
779,Stirling Moss,73,25.205479,1.215909,0.000000,10.568555
765,Sebastian Vettel,300,24.566667,1.391807,0.571429,10.497675
168,Damon Hill,122,22.950820,2.230351,0.142857,10.101040
617,Nigel Mansell,192,20.520833,1.305723,0.142857,8.759194
618,Niki Lauda,174,19.367816,1.531853,0.428571,8.445582
583,Mika Häkkinen,165,17.757576,1.317645,0.285714,7.687231
393,James Hunt,93,14.946237,2.615789,0.142857,7.053382
614,Nico Rosberg,206,16.116505,1.293485,0.142857,6.992567
436,Jody Scheckter,113,14.955752,1.867590,0.142857,6.757909
376,Jack Brabham,129,14.806202,1.612909,0.428571,6.653358
127,Carlos Reutemann,146,15.000000,1.486083,0.000000,6.594433
477,Juan Pablo Montoya,95,14.631579,1.336823,0.000000,6.387361
256,Fernando Alonso,404,13.415842,2.266861,0.285714,6.330224
435,Jochen Rindt,62,13.064516,2.453947,0.142857,6.235957
191,Denny Hulme,112,13.839286,1.194541,0.142857,6.042102
11,Alan Jones,117,13.333333,1.264243,0.142857,5.867602
502,Kimi Räikkönen,352,12.954545,1.562003,0.142857,5.835191
681,Phil Hill,52,13.269231,1.151515,0.142857,5.796870
132,Charles Leclerc,149,12.416107,1.438905,0.000000,5.542005
319,Graham Hill,179,11.508380,2.194995,0.285714,5.538493

In [97]:
import numpy as np

In [98]:
driver_alpha = driver_alpha.replace(
    [np.inf, -np.inf],
    np.nan
)

driver_alpha = driver_alpha.fillna(0)

driver_alpha[
    driver_alpha['Races'] >= 50
].sort_values(
    'Driver_Alpha_V1',
    ascending=False
)[[
    'driver_name',
    'Driver_Alpha_V1'
]].head(30)

            driver_name  Driver_Alpha_V1
415           Jim Clark        25.967199
474         Juan Fangio        19.958704
571      Max Verstappen        15.798915
523      Lewis Hamilton        15.797196
578  Michael Schumacher        15.435831
62         Ayrton Senna        15.103535
8           Alain Prost        14.365077
385      Jackie Stewart        13.604528
608       Nelson Piquet        11.170090
779       Stirling Moss        10.568555
765    Sebastian Vettel        10.497675
168          Damon Hill        10.101040
617       Nigel Mansell         8.759194
618          Niki Lauda         8.445582
583       Mika Häkkinen         7.687231
393          James Hunt         7.053382
614        Nico Rosberg         6.992567
436      Jody Scheckter         6.757909
376        Jack Brabham         6.653358
127    Carlos Reutemann         6.594433
477  Juan Pablo Montoya         6.387361
256     Fernando Alonso         6.330224
435        Jochen Rindt         6.235957
191         Denny Hulme         6.042102
11           Alan Jones         5.867602
502      Kimi Räikkönen         5.835191
681           Phil Hill         5.796870
132     Charles Leclerc         5.542005
319         Graham Hill         5.538493
752     Ronnie Peterson         5.213008

In [99]:
driver_alpha['Championships'] = (
    driver_alpha['Championship_Score'] * 7
)

driver_alpha[['driver_name','Championships']].sort_values(
    'Championships',
    ascending=False
).head(20)

            driver_name  Championships
523      Lewis Hamilton            7.0
578  Michael Schumacher            7.0
474         Juan Fangio            5.0
765    Sebastian Vettel            4.0
571      Max Verstappen            4.0
8           Alain Prost            4.0
618          Niki Lauda            3.0
376        Jack Brabham            3.0
62         Ayrton Senna            3.0
608       Nelson Piquet            3.0
385      Jackie Stewart            3.0
256     Fernando Alonso            2.0
16       Alberto Ascari            2.0
415           Jim Clark            2.0
583       Mika Häkkinen            2.0
319         Graham Hill            2.0
228  Emerson Fittipaldi            2.0
390  Jacques Villeneuve            1.0
681           Phil Hill            1.0
492        Keke Rosberg            1.0

In [100]:
driver_alpha['Longevity_Score'] = (
    driver_alpha['Races'] /
    driver_alpha['Races'].max()
)

driver_alpha[['driver_name','Races','Longevity_Score']].sort_values(
    'Longevity_Score',
    ascending=False
).head(20)

              driver_name  Races  Longevity_Score
256       Fernando Alonso    404         1.000000
523        Lewis Hamilton    356         0.881188
502        Kimi Räikkönen    352         0.871287
754    Rubens Barrichello    326         0.806931
411         Jenson Button    309         0.764851
578    Michael Schumacher    308         0.762376
765      Sebastian Vettel    300         0.742574
768          Sergio Pérez    283         0.700495
254          Felipe Massa    271         0.670792
718      Riccardo Patrese    257         0.636139
170      Daniel Ricciardo    257         0.636139
397          Jarno Trulli    256         0.633663
831       Valtteri Bottas    247         0.611386
180       David Coulthard    247         0.611386
302  Giancarlo Fisichella    231         0.571782
613       Nico Hülkenberg    230         0.569307
556           Mark Webber    217         0.537129
580      Michele Alboreto    215         0.532178
42      Andrea de Cesaris    214         0.529703
296        Gerhard Berger    210         0.519802

In [101]:
driver_alpha['Driver_Alpha_V2'] = (
    driver_alpha['Opportunity_Score'] * 0.35 +
    driver_alpha['Avg_Outperformance'] * 0.30 +
    driver_alpha['Championships'] * 0.20 +
    driver_alpha['Longevity_Score'] * 0.15
)

driver_alpha[
    driver_alpha['Races'] >= 50
].sort_values(
    'Driver_Alpha_V2',
    ascending=False
)[[
    'driver_name',
    'Races',
    'Championships',
    'Driver_Alpha_V2'
]].head(30)

            driver_name  Races  Championships  Driver_Alpha_V2
415           Jim Clark     73            2.0        21.715810
474         Juan Fangio     58            5.0        18.236868
523      Lewis Hamilton    356            7.0        15.113502
578  Michael Schumacher    308            7.0        14.730191
571      Max Verstappen    209            4.0        14.499923
62         Ayrton Senna    162            3.0        13.550058
8           Alain Prost    202            4.0        13.233886
385      Jackie Stewart    100            3.0        12.366239
765    Sebastian Vettel    300            4.0         9.927261
608       Nelson Piquet    207            3.0         9.813810
779       Stirling Moss     73            0.0         9.213794
168          Damon Hill    122            1.0         8.947189
618          Niki Lauda    174            3.0         7.902896
617       Nigel Mansell    192            1.0         7.845296
583       Mika Häkkinen    165            2.0         7.071707
376        Jack Brabham    129            3.0         6.313939
614        Nico Rosberg    206            1.0         6.305307
393          James Hunt     93            1.0         6.250449
436      Jody Scheckter    113            1.0         6.036746
256     Fernando Alonso    404            2.0         5.925603
127    Carlos Reutemann    146            0.0         5.750033
477  Juan Pablo Montoya     95            0.0         5.557372
435        Jochen Rindt     62            1.0         5.531785
191         Denny Hulme    112            1.0         5.443696
502      Kimi Räikkönen    352            1.0         5.333385
11           Alan Jones    117            1.0         5.289380
228  Emerson Fittipaldi    149            2.0         5.223778
681           Phil Hill     52            1.0         5.208992
319         Graham Hill    179            2.0         5.152892
132     Charles Leclerc    149            0.0         4.832631

In [102]:
driver_alpha[['Opportunity_Score',
              'Avg_Outperformance',
              'Championships',
              'Longevity_Score']].describe()

       Opportunity_Score  Avg_Outperformance  Championships  Longevity_Score
count         861.000000          861.000000     861.000000       861.000000
mean            2.085799            0.247419       0.087108         0.076928
std             5.964236            1.143234       0.539667         0.139268
min             0.000000            0.000000       0.000000         0.002475
25%             0.000000            0.000000       0.000000         0.004950
50%             0.000000            0.000000       0.000000         0.017327
75%             0.161290            0.000000       0.000000         0.074257
max            50.000000           27.651852       7.000000         1.000000

In [103]:
driver_alpha['Opportunity_Norm'] = (
    driver_alpha['Opportunity_Score'] /
    driver_alpha['Opportunity_Score'].max()
)

driver_alpha['Outperformance_Norm'] = (
    driver_alpha['Avg_Outperformance'] /
    driver_alpha['Avg_Outperformance'].max()
)

driver_alpha['Championship_Norm'] = (
    driver_alpha['Championships'] /
    driver_alpha['Championships'].max()
)

driver_alpha['Longevity_Norm'] = (
    driver_alpha['Longevity_Score'] /
    driver_alpha['Longevity_Score'].max()
)

driver_alpha[[
    'Opportunity_Norm',
    'Outperformance_Norm',
    'Championship_Norm',
    'Longevity_Norm'
]].describe()

,Opportunity_Norm,Outperformance_Norm,Championship_Norm,Longevity_Norm
count,861.000000,861.000000,861.000000,861.000000
mean,0.041716,0.008948,0.012444,0.076928
std,0.119285,0.041344,0.077095,0.139268
min,0.000000,0.000000,0.000000,0.002475
25%,0.000000,0.000000,0.000000,0.004950
50%,0.000000,0.000000,0.000000,0.017327
75%,0.003226,0.000000,0.000000,0.074257
max,1.000000,1.000000,1.000000,1.000000

In [104]:
driver_alpha['Driver_Alpha_V3'] = (
    driver_alpha['Opportunity_Norm'] * 0.35 +
    driver_alpha['Outperformance_Norm'] * 0.30 +
    driver_alpha['Championship_Norm'] * 0.20 +
    driver_alpha['Longevity_Norm'] * 0.15
)

driver_alpha[
    driver_alpha['Races'] >= 50
].sort_values(
    'Driver_Alpha_V3',
    ascending=False
)[[
    'driver_name',
    'Driver_Alpha_V3',
    'Opportunity_Norm',
    'Outperformance_Norm',
    'Championship_Norm',
    'Longevity_Norm'
]].head(30)

,driver_name,Driver_Alpha_V3,Opportunity_Norm,Outperformance_Norm,Championship_Norm,Longevity_Norm
415,Jim Clark,0.644110,0.742466,1.000000,0.285714,0.180693
523,Lewis Hamilton,0.610227,0.753371,0.047897,1.000000,0.881188
578,Michael Schumacher,0.589876,0.715584,0.083552,1.000000,0.762376
474,Juan Fangio,0.520679,0.941379,0.089349,0.714286,0.143564
571,Max Verstappen,0.474197,0.743541,0.073577,0.571429,0.517327
8,Alain Prost,0.447186,0.668317,0.079963,0.571429,0.500000
62,Ayrton Senna,0.427973,0.650617,0.181315,0.428571,0.400990
765,Sebastian Vettel,0.412738,0.491333,0.050333,0.571429,0.742574
608,Nelson Piquet,0.399803,0.329469,0.406393,0.428571,0.512376
385,Jackie Stewart,0.367109,0.636000,0.072221,0.428571,0.247525
256,Fernando Alonso,0.325647,0.268317,0.081979,0.285714,1.000000
618,Niki Lauda,0.302512,0.387356,0.055398,0.428571,0.430693
502,Kimi Räikkönen,0.266893,0.259091,0.056488,0.142857,0.871287
168,Damon Hill,0.258722,0.459016,0.080658,0.142857,0.301980
617,Nigel Mansell,0.257670,0.410417,0.047220,0.142857,0.475248
583,Mika Häkkinen,0.257004,0.355152,0.047651,0.285714,0.408416
376,Jack Brabham,0.254752,0.296124,0.058329,0.428571,0.319307
614,Nico Rosberg,0.231905,0.322330,0.046778,0.142857,0.509901
319,Graham Hill,0.227976,0.230168,0.079380,0.285714,0.443069
411,Jenson Button,0.217425,0.165049,0.054529,0.142857,0.764851
779,Stirling Moss,0.216734,0.504110,0.043972,0.000000,0.180693
228,Emerson Fittipaldi,0.207834,0.272483,0.000000,0.285714,0.368812
393,James Hunt,0.196104,0.298925,0.094597,0.142857,0.230198
436,Jody Scheckter,0.195479,0.299115,0.067539,0.142857,0.279703
754,Rubens Barrichello,0.193596,0.172393,0.040730,0.000000,0.806931
831,Valtteri Bottas,0.188941,0.219433,0.068105,0.000000,0.611386
180,David Coulthard,0.183010,0.224291,0.042668,0.000000,0.611386
191,Denny Hulme,0.179990,0.276786,0.043199,0.142857,0.277228
11,Alan Jones,0.179061,0.266667,0.045720,0.142857,0.289604
127,Carlos Reutemann,0.175331,0.300000,0.053743,0.000000,0.361386

In [105]:
qualifying_merge.columns

Index(['qualifyId', 'raceId', 'driverId', 'constructorId', 'number',
       'position', 'q1', 'q2', 'q3', 'year'],
      dtype='object')

In [106]:
qualifying_drivers = qualifying_merge.merge(
    drivers[['driverId','driver_name']],
    on='driverId',
    how='left'
)

qualifying_drivers.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3,year,driver_name
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714,2008,Lewis Hamilton
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869,2008,Robert Kubica
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079,2008,Heikki Kovalainen
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178,2008,Felipe Massa
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236,2008,Nick Heidfeld

In [107]:
qualifying_drivers[['driver_name','year','position']].head()

         driver_name  year  position
0     Lewis Hamilton  2008         1
1      Robert Kubica  2008         2
2  Heikki Kovalainen  2008         3
3       Felipe Massa  2008         4
4      Nick Heidfeld  2008         5

In [108]:
qualifying_avg = (
    qualifying_drivers.groupby('driver_name')
    .agg(
        Qualifying_Avg_Position=('position','mean'),
        Qualifying_Sessions=('position','count')
    )
    .reset_index()
)

qualifying_avg[
    qualifying_avg['Qualifying_Sessions'] >= 20
].sort_values(
    'Qualifying_Avg_Position'
).head(30)

               driver_name  Qualifying_Avg_Position  Qualifying_Sessions
84          Lewis Hamilton                 4.073034                  356
97          Max Verstappen                 4.727273                  209
25              Damon Hill                 5.372881                   59
98      Michael Schumacher                 5.666667                  192
45          Gerhard Berger                 5.760870                   46
71      Juan Pablo Montoya                 6.031250                   64
101          Mika Häkkinen                 6.048387                   62
19         Charles Leclerc                 6.208054                  149
146       Sebastian Vettel                 6.247492                  299
108           Nico Rosberg                 6.834951                  206
83            Lando Norris                 7.218750                  128
92             Mark Webber                 7.316832                  202
62              Jean Alesi                 7.467742                   62
118          Oscar Piastri                 7.543478                   46
81          Kimi Räikkönen                 7.654206                  321
162        Valtteri Bottas                 7.846154                  247
38         Fernando Alonso                 8.139535                  387
132        Ralf Schumacher                 8.261682                  107
31            Eddie Irvine                 8.265625                   64
36            Felipe Massa                 8.357977                  257
18            Carlos Sainz                 8.512077                  207
54   Heinz-Harald Frentzen                 9.037037                   81
29         David Coulthard                 9.193939                  165
143     Rubens Barrichello                 9.269912                  226
67           Jenson Button                 9.334601                  263
58      Jacques Villeneuve                 9.542169                   83
26        Daniel Ricciardo                 9.792969                  256
148           Sergio Pérez                 9.900709                  282
44          George Russell                10.328125                  128
138          Robert Kubica                10.585859                   99

In [109]:
qualifying_avg['Qualifying_Score'] = (
    1 /
    qualifying_avg['Qualifying_Avg_Position']
)

qualifying_avg.sort_values(
    'Qualifying_Score',
    ascending=False
).head(30)

,driver_name,Qualifying_Avg_Position,Qualifying_Sessions,Qualifying_Score
14,Ayrton Senna,1.000000,3,1.000000
84,Lewis Hamilton,4.073034,356,0.245517
97,Max Verstappen,4.727273,209,0.211538
111,Nigel Mansell,4.833333,6,0.206897
25,Damon Hill,5.372881,59,0.186120
98,Michael Schumacher,5.666667,192,0.176471
45,Gerhard Berger,5.760870,46,0.173585
71,Juan Pablo Montoya,6.031250,64,0.165803
101,Mika Häkkinen,6.048387,62,0.165333
19,Charles Leclerc,6.208054,149,0.161081
146,Sebastian Vettel,6.247492,299,0.160064
108,Nico Rosberg,6.834951,206,0.146307
83,Lando Norris,7.218750,128,0.138528
92,Mark Webber,7.316832,202,0.136671
62,Jean Alesi,7.467742,62,0.133909
118,Oscar Piastri,7.543478,46,0.132565
81,Kimi Räikkönen,7.654206,321,0.130647
162,Valtteri Bottas,7.846154,247,0.127451
38,Fernando Alonso,8.139535,387,0.122857
132,Ralf Schumacher,8.261682,107,0.121041
31,Eddie Irvine,8.265625,64,0.120983
36,Felipe Massa,8.357977,257,0.119646
18,Carlos Sainz,8.512077,207,0.117480
54,Heinz-Harald Frentzen,9.037037,81,0.110656
29,David Coulthard,9.193939,165,0.108767
143,Rubens Barrichello,9.269912,226,0.107876
67,Jenson Button,9.334601,263,0.107128
58,Jacques Villeneuve,9.542169,83,0.104798
26,Daniel Ricciardo,9.792969,256,0.102114
148,Sergio Pérez,9.900709,282,0.101003

In [110]:
qualifying_avg[
    qualifying_avg['Qualifying_Sessions'] >= 50
].sort_values(
    'Qualifying_Score',
    ascending=False
).head(30)

,driver_name,Qualifying_Avg_Position,Qualifying_Sessions,Qualifying_Score
84,Lewis Hamilton,4.073034,356,0.245517
97,Max Verstappen,4.727273,209,0.211538
25,Damon Hill,5.372881,59,0.186120
98,Michael Schumacher,5.666667,192,0.176471
71,Juan Pablo Montoya,6.031250,64,0.165803
101,Mika Häkkinen,6.048387,62,0.165333
19,Charles Leclerc,6.208054,149,0.161081
146,Sebastian Vettel,6.247492,299,0.160064
108,Nico Rosberg,6.834951,206,0.146307
83,Lando Norris,7.218750,128,0.138528
92,Mark Webber,7.316832,202,0.136671
62,Jean Alesi,7.467742,62,0.133909
81,Kimi Räikkönen,7.654206,321,0.130647
162,Valtteri Bottas,7.846154,247,0.127451
38,Fernando Alonso,8.139535,387,0.122857
132,Ralf Schumacher,8.261682,107,0.121041
31,Eddie Irvine,8.265625,64,0.120983
36,Felipe Massa,8.357977,257,0.119646
18,Carlos Sainz,8.512077,207,0.117480
54,Heinz-Harald Frentzen,9.037037,81,0.110656
29,David Coulthard,9.193939,165,0.108767
143,Rubens Barrichello,9.269912,226,0.107876
67,Jenson Button,9.334601,263,0.107128
58,Jacques Villeneuve,9.542169,83,0.104798
26,Daniel Ricciardo,9.792969,256,0.102114
148,Sergio Pérez,9.900709,282,0.101003
44,George Russell,10.328125,128,0.096823
138,Robert Kubica,10.585859,99,0.094466
107,Nico Hülkenberg,10.650655,229,0.093891
61,Jarno Trulli,11.026882,186,0.090687

In [111]:
lap_times = pd.read_csv("lap_times.csv")

In [112]:
lap_times.shape

(589081, 6)

In [113]:
lap_times.head()

   raceId  driverId  lap  position      time  milliseconds
0     841        20    1         1  1:38.109         98109
1     841        20    2         1  1:33.006         93006
2     841        20    3         1  1:32.713         92713
3     841        20    4         1  1:32.803         92803
4     841        20    5         1  1:32.342         92342

In [114]:
lap_times.columns

Index(['raceId', 'driverId', 'lap', 'position', 'time', 'milliseconds'], dtype='object')

In [115]:
lap_avg = (
    lap_times.groupby('driverId')
    .agg(
        Avg_Lap_Time=('milliseconds','mean'),
        Total_Laps=('lap','count')
    )
    .reset_index()
)

lap_avg.sort_values(
    'Avg_Lap_Time'
).head(20)

     driverId  Avg_Lap_Time  Total_Laps
131       851  63319.402299          87
130       850  80792.571429         140
71         72  82907.903226          31
42         43  86875.075472        1484
30         31  86976.960138        4917
65         66  87315.032864         639
35         36  87851.812500         240
53         54  88575.052395         668
25         26  89131.074708        1285
51         52  89165.956182         639
60         61  89210.228916         166
52         53  89416.620805         298
44         45  89550.812386         549
13         14  89663.810722       11211
79         81  89921.912676         355
50         51  89954.638806         670
34         35  90217.315131        8314
22         23  90227.545603        9166
31         32  90397.104247        2331
39         40  90529.864078         412

In [116]:
lap_times['driverId'].nunique()

143

In [117]:
lap_times['raceId'].nunique()

544

In [118]:
lap_times['position'].describe()

count    589081.000000
mean          9.661951
std           5.528553
min           1.000000
25%           5.000000
50%           9.000000
75%          14.000000
max          24.000000
Name: position, dtype: float64

In [119]:
race_position = (
    lap_times.groupby('driverId')
    .agg(
        Avg_Race_Position=('position','mean'),
        Total_Laps=('lap','count')
    )
    .reset_index()
)

race_position[
    race_position['Total_Laps'] >= 1000
].sort_values(
    'Avg_Race_Position'
).head(30)

     driverId  Avg_Race_Position  Total_Laps
56         57           3.698608        4957
0           1           4.037493       20297
110       830           4.046740       11318
29         30           4.654238       13168
30         31           4.732967        4917
19         20           5.639983       16427
124       844           5.956116        7930
7           8           6.576330       18623
2           3           6.653884       11161
13         14           6.805548       11211
70         71           6.986564        2977
3           4           7.096294       21829
76         77           7.146650        1582
55         56           7.495564        5523
126       846           7.498015        7303
137       857           7.510841        2629
16         17           7.591766       11028
22         23           7.626118        9166
48         49           7.728520        5831
21         22           7.742723       14463
112       832           7.807537       11119
12         13           7.930254       14854
34         35           8.076257        8314
102       822           8.110021       13861
54         55           8.118891        4870
17         18           8.412303       16272
95        815           8.433219       15491
97        817           9.352841       14131
20         21           9.405769       11509
8           9           9.709718        5505

In [120]:
drivers['driver_name'] = (
    drivers['forename'] + ' ' + drivers['surname']
)

race_position = race_position.merge(
    drivers[['driverId','driver_name']],
    on='driverId',
    how='left'
)

race_position[
    race_position['Total_Laps'] >= 1000
].sort_values(
    'Avg_Race_Position'
)[[
    'driver_name',
    'Avg_Race_Position',
    'Total_Laps'
]].head(30)

               driver_name  Avg_Race_Position  Total_Laps
56           Mika Häkkinen           3.698608        4957
0           Lewis Hamilton           4.037493       20297
110         Max Verstappen           4.046740       11318
29      Michael Schumacher           4.654238       13168
30      Juan Pablo Montoya           4.732967        4917
19        Sebastian Vettel           5.639983       16427
124        Charles Leclerc           5.956116        7930
7           Kimi Räikkönen           6.576330       18623
2             Nico Rosberg           6.653884       11161
13         David Coulthard           6.805548       11211
70              Damon Hill           6.986564        2977
3          Fernando Alonso           7.096294       21829
76          Gerhard Berger           7.146650        1582
55            Eddie Irvine           7.495564        5523
126           Lando Norris           7.498015        7303
137          Oscar Piastri           7.510841        2629
16             Mark Webber           7.591766       11028
22         Ralf Schumacher           7.626118        9166
48   Heinz-Harald Frentzen           7.728520        5831
21      Rubens Barrichello           7.742723       14463
112           Carlos Sainz           7.807537       11119
12            Felipe Massa           7.930254       14854
34      Jacques Villeneuve           8.076257        8314
102        Valtteri Bottas           8.110021       13861
54              Jean Alesi           8.118891        4870
17           Jenson Button           8.412303       16272
95            Sergio Pérez           8.433219       15491
97        Daniel Ricciardo           9.352841       14131
20    Giancarlo Fisichella           9.405769       11509
8            Robert Kubica           9.709718        5505

In [121]:
race_position['Race_Pace_Score'] = (
    1 /
    race_position['Avg_Race_Position']
)

race_position.sort_values(
    'Race_Pace_Score',
    ascending=False
)[[
    'driver_name',
    'Avg_Race_Position',
    'Race_Pace_Score'
]].head(30)

               driver_name  Avg_Race_Position  Race_Pace_Score
56           Mika Häkkinen           3.698608         0.270372
0           Lewis Hamilton           4.037493         0.247678
110         Max Verstappen           4.046740         0.247113
29      Michael Schumacher           4.654238         0.214858
30      Juan Pablo Montoya           4.732967         0.211284
19        Sebastian Vettel           5.639983         0.177306
124        Charles Leclerc           5.956116         0.167895
7           Kimi Räikkönen           6.576330         0.152060
2             Nico Rosberg           6.653884         0.150288
13         David Coulthard           6.805548         0.146939
70              Damon Hill           6.986564         0.143132
3          Fernando Alonso           7.096294         0.140919
76          Gerhard Berger           7.146650         0.139926
55            Eddie Irvine           7.495564         0.133412
126           Lando Norris           7.498015         0.133369
137          Oscar Piastri           7.510841         0.133141
16             Mark Webber           7.591766         0.131722
22         Ralf Schumacher           7.626118         0.131128
48   Heinz-Harald Frentzen           7.728520         0.129391
21      Rubens Barrichello           7.742723         0.129154
27       Markus Winkelhock           7.769231         0.128713
112           Carlos Sainz           7.807537         0.128081
12            Felipe Massa           7.930254         0.126099
82          Martin Brundle           8.075177         0.123836
34      Jacques Villeneuve           8.076257         0.123820
102        Valtteri Bottas           8.110021         0.123304
54              Jean Alesi           8.118891         0.123170
17           Jenson Button           8.412303         0.118874
95            Sergio Pérez           8.433219         0.118579
97        Daniel Ricciardo           9.352841         0.106919

In [122]:
pit_stops = pd.read_csv("pit_stops.csv")

In [123]:
pit_stops.head()

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

In [124]:
pit_stops.shape

(11371, 7)

In [125]:
pit_stops['milliseconds'].describe()

count    1.137100e+04
mean     8.523050e+04
std      3.104273e+05
min      1.289700e+04
25%      2.193750e+04
50%      2.360600e+04
75%      2.654400e+04
max      3.069017e+06
Name: milliseconds, dtype: float64

In [126]:
pit_stops[
    pit_stops['milliseconds'] < 60000
]['milliseconds'].describe()

count    10854.000000
mean     24448.585498
std       4606.013128
min      12897.000000
25%      21864.000000
50%      23428.500000
75%      25639.750000
max      59555.000000
Name: milliseconds, dtype: float64

In [127]:
clean_pits = pit_stops[
    pit_stops['milliseconds'] < 60000
].copy()

pit_driver = (
    clean_pits.groupby('driverId')
    .agg(
        Avg_Pit_Stop=('milliseconds','mean'),
        Pit_Stops=('milliseconds','count')
    )
    .reset_index()
)

pit_driver[
    pit_driver['Pit_Stops'] >= 20
].sort_values(
    'Avg_Pit_Stop'
).head(30)

    driverId  Avg_Pit_Stop  Pit_Stops
16        30  22541.644444         90
11        17  22574.382979        141
1          2  22933.320000         25
2          3  23266.688525        244
28       814  23298.230159        126
12        18  23379.422925        253
0          1  23522.747628        527
24       808  23694.160920         87
8         13  23721.795455        308
13        20  23735.306306        444
7         10  23743.946667         75
3          4  23823.755556        450
20       153  23862.348837         43
25       811  23938.557377         61
56       843  23993.911765         34
19        67  24024.317073         41
10        16  24109.264957        117
29       815  24110.399610        513
27       813  24157.963731        193
31       817  24188.357942        447
43       830  24222.754190        358
32       818  24292.048387        124
57       844  24345.773913        230
70       857  24391.120000         75
6          9  24428.738095         42
37       823  24441.020408         49
22       155  24467.820755        106
5          8  24538.732353        340
53       840  24581.606498        277
23       807  24603.187166        374

In [128]:
results[['driverId','constructorId']].head()

   driverId  constructorId
0         1              1
1         2              2
2         3              3
3         4              4
4         5              1

In [129]:
results[['raceId','driverId','constructorId']].head()

   raceId  driverId  constructorId
0      18         1              1
1      18         2              2
2      18         3              3
3      18         4              4
4      18         5              1

In [130]:
pit_team = clean_pits.merge(
    results[['raceId','driverId','constructorId']],
    on=['raceId','driverId'],
    how='left'
)

pit_team.head()

   raceId  driverId  stop  lap      time duration  milliseconds  constructorId
0     841       153     1    1  17:05:23   26.898         26898              5
1     841        30     1    1  17:05:52   25.021         25021            131
2     841        17     1   11  17:20:48   23.426         23426              9
3     841         4     1   12  17:22:34   23.251         23251              6
4     841        13     1   13  17:24:10   23.842         23842              6

In [131]:
pit_team.shape

(10854, 8)

In [132]:
constructors[['constructorId','constructorRef']].head()

   constructorId constructorRef
0              1        mclaren
1              2     bmw_sauber
2              3       williams
3              4        renault
4              5     toro_rosso

In [133]:
pit_team = pit_team.merge(
    constructors[['constructorId','constructorRef']],
    on='constructorId',
    how='left'
)

pit_team.head()

,raceId,driverId,stop,lap,time,duration,milliseconds,constructorId,constructorRef
0,841,153,1,1,17:05:23,26.898,26898,5,toro_rosso
1,841,30,1,1,17:05:52,25.021,25021,131,mercedes
2,841,17,1,11,17:20:48,23.426,23426,9,red_bull
3,841,4,1,12,17:22:34,23.251,23251,6,ferrari
4,841,13,1,13,17:24:10,23.842,23842,6,ferrari

In [134]:
team_pits = (
    pit_team.groupby('constructorRef')
    .agg(
        Avg_Pit_Stop=('milliseconds','mean'),
        Total_Pit_Stops=('milliseconds','count')
    )
    .reset_index()
)

team_pits[
    team_pits['Total_Pit_Stops'] >= 20
].sort_values(
    'Avg_Pit_Stop'
).head(30)

   constructorRef  Avg_Pit_Stop  Total_Pit_Stops
17       red_bull  23695.818942             1077
14       mercedes  23705.930871             1056
5         ferrari  23860.779710             1035
6     force_india  24058.360877              593
13        mclaren  24171.041426             1038
21         virgin  24236.194805               77
9        lotus_f1  24238.224199              281
18        renault  24297.161538              390
10   lotus_racing  24444.211765               85
20     toro_rosso  24491.064083              671
3    aston_martin  24531.735974              303
22       williams  24683.181051             1066
16             rb  24733.666667               72
2          alpine  24754.859206              277
4        caterham  24805.861925              239
12       marussia  24869.341991              231
19         sauber  24990.623547              688
1      alphatauri  24995.389474              285
15   racing_point  25317.126126              111
0            alfa  25562.947522              343
7            haas  25568.371473              638
8             hrt  26154.006711              149
11          manor  26395.483221              149

In [135]:
team_pits['Operational_Efficiency_Score'] = (
    team_pits['Avg_Pit_Stop'].min() /
    team_pits['Avg_Pit_Stop']
)

In [136]:
team_pits.sort_values(
    'Operational_Efficiency_Score',
    ascending=False
).head(20)

   constructorRef  Avg_Pit_Stop  Total_Pit_Stops  Operational_Efficiency_Score
17       red_bull  23695.818942             1077                      1.000000
14       mercedes  23705.930871             1056                      0.999573
5         ferrari  23860.779710             1035                      0.993087
6     force_india  24058.360877              593                      0.984931
13        mclaren  24171.041426             1038                      0.980339
21         virgin  24236.194805               77                      0.977704
9        lotus_f1  24238.224199              281                      0.977622
18        renault  24297.161538              390                      0.975251
10   lotus_racing  24444.211765               85                      0.969384
20     toro_rosso  24491.064083              671                      0.967529
3    aston_martin  24531.735974              303                      0.965925
22       williams  24683.181051             1066                      0.959999
16             rb  24733.666667               72                      0.958039
2          alpine  24754.859206              277                      0.957219
4        caterham  24805.861925              239                      0.955251
12       marussia  24869.341991              231                      0.952812
19         sauber  24990.623547              688                      0.948188
1      alphatauri  24995.389474              285                      0.948008
15   racing_point  25317.126126              111                      0.935960
0            alfa  25562.947522              343                      0.926960

In [137]:
team_pits.to_csv(
    "team_operational_efficiency.csv",
    index=False
)

In [138]:
driver_alpha.columns

Index(['driver_name', 'Races', 'Wins', 'Podiums', 'Total_Points', 'Win_Rate',
       'Podium_Rate', 'Opportunity_Score', 'Seasons', 'Avg_Outperformance',
       'Championship_Score', 'Driver_Alpha_V1', 'Championships',
       'Longevity_Score', 'Driver_Alpha_V2', 'Opportunity_Norm',
       'Outperformance_Norm', 'Championship_Norm', 'Longevity_Norm',
       'Driver_Alpha_V3'],
      dtype='object')

In [139]:
%who DataFrame

career_outperformance	 champions	 championships	 championships_named	 clean_pits	 constructor_strength	 constructors	 constructors_standings	 driver_alpha
driver_alpha_teammate	 driver_standings	 driver_summary	 drivers	 final_standings	 head_to_head	 lap_avg	 lap_times	 leader_points
merged	 pit_driver	 pit_stops	 pit_team	 qualified_drivers	 qualifying	 qualifying_avg	 qualifying_drivers	 qualifying_merge
race_position	 races	 results	 season_finals	 second_driver	 status	 team_drivers	 team_pits	 team_rankings
team_totals	 teammate_compare	 teammate_counts	 teammate_data	 teammate_filtered	 top_drivers	 top_teammates

In [140]:
qualifying_avg.columns

Index(['driver_name', 'Qualifying_Avg_Position', 'Qualifying_Sessions',
       'Qualifying_Score'],
      dtype='object')

In [141]:
race_position.columns

Index(['driverId', 'Avg_Race_Position', 'Total_Laps', 'driver_name',
       'Race_Pace_Score'],
      dtype='object')

In [142]:
master_driver = driver_alpha.merge(
    qualifying_avg[
        ['driver_name','Qualifying_Score']
    ],
    on='driver_name',
    how='left'
)

master_driver = master_driver.merge(
    race_position[
        ['driver_name','Race_Pace_Score']
    ],
    on='driver_name',
    how='left'
)

master_driver.head()

,driver_name,Races,Wins,Podiums,Total_Points,Win_Rate,Podium_Rate,Opportunity_Score,Seasons,Avg_Outperformance,...,Championships,Longevity_Score,Driver_Alpha_V2,Opportunity_Norm,Outperformance_Norm,Championship_Norm,Longevity_Norm,Driver_Alpha_V3,Qualifying_Score,Race_Pace_Score
0,Adolf Brudes,1,0,0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.002475,0.000371,0.000000,0.000000,0.0,0.002475,0.000371,NaN,NaN
1,Adolfo Cruz,1,0,0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.002475,0.000371,0.000000,0.000000,0.0,0.002475,0.000371,NaN,NaN
2,Adrian Sutil,128,0,0,124.0,0.0,0.000000,0.000000,3.0,1.597884,...,0.0,0.316832,0.526890,0.000000,0.057786,0.0,0.316832,0.064860,0.067368,0.076683
3,Adrián Campos,21,0,0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.051980,0.007797,0.000000,0.000000,0.0,0.051980,0.007797,NaN,NaN
4,Aguri Suzuki,88,0,1,8.0,0.0,0.011364,0.340909,0.0,0.000000,...,0.0,0.217822,0.151991,0.006818,0.000000,0.0,0.217822,0.035060,0.061404,NaN

In [143]:
master_driver.columns

Index(['driver_name', 'Races', 'Wins', 'Podiums', 'Total_Points', 'Win_Rate',
       'Podium_Rate', 'Opportunity_Score', 'Seasons', 'Avg_Outperformance',
       'Championship_Score', 'Driver_Alpha_V1', 'Championships',
       'Longevity_Score', 'Driver_Alpha_V2', 'Opportunity_Norm',
       'Outperformance_Norm', 'Championship_Norm', 'Longevity_Norm',
       'Driver_Alpha_V3', 'Qualifying_Score', 'Race_Pace_Score'],
      dtype='object')

In [144]:
master_driver.to_csv(
    "master_driver_dataset.csv",
    index=False
)

In [145]:
master_driver[
    ['Qualifying_Score','Race_Pace_Score']
].isna().sum()

Qualifying_Score    689
Race_Pace_Score     718
dtype: int64

In [146]:
master_driver.to_csv(
    "master_driver_dataset.csv",
    index=False
)

master_driver.shape

(861, 22)

In [147]:
constructor_strength.columns

Index(['year', 'constructorRef', 'Team_Points', 'Car_Strength_Score'], dtype='object')

In [148]:
constructors_standings.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0

In [149]:
races[['raceId','year']].head()

   raceId  year
0       1  2009
1       2  2009
2       3  2009
3       4  2009
4       5  2009

In [150]:
constructors[['constructorId','constructorRef']].head()

   constructorId constructorRef
0              1        mclaren
1              2     bmw_sauber
2              3       williams
3              4        renault
4              5     toro_rosso

In [151]:
constructor_year = constructors_standings.merge(
    races[['raceId','year']],
    on='raceId',
    how='left'
)

constructor_year = constructor_year.merge(
    constructors[['constructorId','constructorRef']],
    on='constructorId',
    how='left'
)

constructor_year.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins,year,constructorRef
0,1,18,1,14.0,1,1,1,2008,mclaren
1,2,18,2,8.0,3,3,0,2008,bmw_sauber
2,3,18,3,9.0,2,2,0,2008,williams
3,4,18,4,5.0,4,4,0,2008,renault
4,5,18,5,2.0,5,5,0,2008,toro_rosso

In [152]:
constructor_year.columns

Index(['constructorStandingsId', 'raceId', 'constructorId', 'points',
       'position', 'positionText', 'wins', 'year', 'constructorRef'],
      dtype='object')

In [153]:
constructor_finals = (
    constructor_year.sort_values('raceId')
    .groupby(['year','constructorRef'])
    .tail(1)
)

constructor_finals.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins,year,constructorRef
8383,13918,17,23,172.0,1,1,8,2009,brawn
8391,13926,17,9,153.5,2,2,6,2009,red_bull
8390,13925,17,2,36.0,6,6,0,2009,bmw_sauber
8389,13924,17,10,13.0,9,9,0,2009,force_india
8388,13923,17,5,8.0,10,10,0,2009,toro_rosso

In [154]:
constructor_finals.columns

Index(['constructorStandingsId', 'raceId', 'constructorId', 'points',
       'position', 'positionText', 'wins', 'year', 'constructorRef'],
      dtype='object')

In [155]:
year_totals = (
    constructor_finals
    .groupby('year')['points']
    .sum()
    .reset_index(name='Season_Total_Points')
)

constructor_finals = constructor_finals.merge(
    year_totals,
    on='year',
    how='left'
)

constructor_finals['Points_Share'] = (
    constructor_finals['points'] /
    constructor_finals['Season_Total_Points']
)

constructor_finals[
    ['year','constructorRef','points','Points_Share']
].head()

   year constructorRef  points  Points_Share
0  2009          brawn   172.0      0.267288
1  2009       red_bull   153.5      0.238539
2  2009     bmw_sauber    36.0      0.055944
3  2009    force_india    13.0      0.020202
4  2009     toro_rosso     8.0      0.012432

In [156]:
season_races = (
    races.groupby('year')['raceId']
    .nunique()
    .reset_index(name='Total_Races')
)

constructor_finals = constructor_finals.merge(
    season_races,
    on='year',
    how='left'
)

constructor_finals['Win_Share'] = (
    constructor_finals['wins'] /
    constructor_finals['Total_Races']
)

constructor_finals[
    ['year','constructorRef','wins','Total_Races','Win_Share']
].head()

   year constructorRef  wins  Total_Races  Win_Share
0  2009          brawn     8           17   0.470588
1  2009       red_bull     6           17   0.352941
2  2009     bmw_sauber     0           17   0.000000
3  2009    force_india     0           17   0.000000
4  2009     toro_rosso     0           17   0.000000

In [157]:
constructor_finals['Car_Dominance_Score'] = (
    0.6 * constructor_finals['Win_Share']
    +
    0.4 * constructor_finals['Points_Share']
)

constructor_finals.sort_values(
    'Car_Dominance_Score',
    ascending=False
)[[
    'year',
    'constructorRef',
    'wins',
    'points',
    'Win_Share',
    'Points_Share',
    'Car_Dominance_Score'
]].head(30)

,year,constructorRef,wins,points,Win_Share,Points_Share,Car_Dominance_Score
281,1988,mclaren,15,199.0,0.937500,0.497500,0.761500
80,2002,ferrari,15,221.0,0.882353,0.500000,0.729412
900,2023,red_bull,21,860.0,0.954545,0.349878,0.712678
836,2016,mercedes,19,765.0,0.904762,0.360679,0.687129
820,2015,mercedes,16,703.0,0.842105,0.366337,0.651798
54,2004,ferrari,15,262.0,0.833333,0.373219,0.649288
817,2014,mercedes,16,701.0,0.842105,0.347030,0.644075
141,1996,williams,12,175.0,0.750000,0.420673,0.618269
355,1984,mclaren,12,143.5,0.750000,0.374185,0.599674
899,2022,red_bull,17,759.0,0.772727,0.322979,0.592828
870,2020,mercedes,13,573.0,0.764706,0.333333,0.592157
869,2019,mercedes,15,739.0,0.714286,0.345327,0.566702
688,1963,lotus-climax,7,54.0,0.700000,0.293478,0.537391
180,1993,williams,10,168.0,0.625000,0.403846,0.536538
801,2013,red_bull,13,596.0,0.684211,0.310578,0.534758
203,1992,williams,10,164.0,0.625000,0.394231,0.532692
726,1961,ferrari,5,45.0,0.625000,0.365854,0.521341
153,1995,benetton,11,147.0,0.647059,0.332579,0.521267
747,1960,cooper-climax,6,48.0,0.600000,0.390244,0.516098
259,1989,mclaren,10,141.0,0.625000,0.352500,0.516000
773,2011,red_bull,12,650.0,0.631579,0.338718,0.514435
571,1971,tyrrell,7,73.0,0.636364,0.320175,0.509888
96,2000,ferrari,10,170.0,0.588235,0.384615,0.506787
763,1959,cooper-climax,5,40.0,0.555556,0.421053,0.501754
846,2017,mercedes,12,668.0,0.600000,0.330693,0.492277
127,1998,mclaren,9,156.0,0.562500,0.375000,0.487500
86,2001,ferrari,9,179.0,0.529412,0.404977,0.479638
318,1986,williams,9,141.0,0.562500,0.352500,0.478500
661,1965,lotus-climax,6,54.0,0.600000,0.293478,0.477391
308,1987,williams,9,137.0,0.562500,0.344221,0.475188

In [158]:
constructor_finals.to_csv(
    "car_dominance_v1.csv",
    index=False
)

In [159]:
constructor_finals['Car_Dominance_V2'] = (
    0.75 * constructor_finals['Win_Share']
    +
    0.25 * constructor_finals['Points_Share']
)

constructor_finals.sort_values(
    'Car_Dominance_V2',
    ascending=False
)[[
    'year',
    'constructorRef',
    'wins',
    'Win_Share',
    'Points_Share',
    'Car_Dominance_V2'
]].head(30)

     year constructorRef  wins  Win_Share  Points_Share  Car_Dominance_V2
281  1988        mclaren    15   0.937500      0.497500          0.827500
900  2023       red_bull    21   0.954545      0.349878          0.803379
80   2002        ferrari    15   0.882353      0.500000          0.786765
836  2016       mercedes    19   0.904762      0.360679          0.768741
820  2015       mercedes    16   0.842105      0.366337          0.723163
817  2014       mercedes    16   0.842105      0.347030          0.718336
54   2004        ferrari    15   0.833333      0.373219          0.718305
141  1996       williams    12   0.750000      0.420673          0.667668
899  2022       red_bull    17   0.772727      0.322979          0.660290
870  2020       mercedes    13   0.764706      0.333333          0.656863
355  1984        mclaren    12   0.750000      0.374185          0.656046
869  2019       mercedes    15   0.714286      0.345327          0.622046
688  1963   lotus-climax     7   0.700000      0.293478          0.598370
801  2013       red_bull    13   0.684211      0.310578          0.590803
180  1993       williams    10   0.625000      0.403846          0.569712
153  1995       benetton    11   0.647059      0.332579          0.568439
203  1992       williams    10   0.625000      0.394231          0.567308
726  1961        ferrari     5   0.625000      0.365854          0.560213
773  2011       red_bull    12   0.631579      0.338718          0.558364
571  1971        tyrrell     7   0.636364      0.320175          0.557317
259  1989        mclaren    10   0.625000      0.352500          0.556875
747  1960  cooper-climax     6   0.600000      0.390244          0.547561
96   2000        ferrari    10   0.588235      0.384615          0.537330
846  2017       mercedes    12   0.600000      0.330693          0.532673
661  1965   lotus-climax     6   0.600000      0.293478          0.523370
763  1959  cooper-climax     5   0.555556      0.421053          0.521930
127  1998        mclaren     9   0.562500      0.375000          0.515625
318  1986       williams     9   0.562500      0.352500          0.510000
308  1987       williams     9   0.562500      0.344221          0.507930
86   2001        ferrari     9   0.529412      0.404977          0.498303

In [160]:
constructor_finals.to_csv(
    "car_dominance_final.csv",
    index=False
)

In [161]:
master_driver.to_csv(
    "master_driver_dataset.csv",
    index=False
)

team_pits.to_csv(
    "team_operational_efficiency.csv",
    index=False
)

constructor_finals.to_csv(
    "car_dominance_final.csv",
    index=False
)

In [162]:
master_driver.shape
team_pits.shape
constructor_finals.shape

(920, 15)

In [163]:
print("master_driver:", master_driver.shape)
print("team_pits:", team_pits.shape)
print("constructor_finals:", constructor_finals.shape)

master_driver: (861, 22)
team_pits: (23, 4)
constructor_finals: (920, 15)

1. Raw points caused era bias in Car Dominance.
   Fixed using Win Share + Points Share.

2. Qualifying data coverage starts around 1994.
   Older drivers have missing qualifying metrics.

3. Race Pace uses available lap-time coverage only.
   Historical coverage is incomplete.

4. Pit stop analysis required raceId + driverId join.
   driverId-only join caused duplication bug.

5. Do not fill missing Qualifying/Race Pace values with 0.
   Keep as NULL because data is unavailable, not poor performance.

6. Opportunity Score and Outperformance may contain some correlation.
   Future version can test weighting sensitivity.

7. Car Dominance V1 tested and rejected.
   Car Dominance V2 selected.

In [165]:
%who DataFrame

career_outperformance	 champions	 championships	 championships_named	 clean_pits	 constructor_finals	 constructor_strength	 constructor_year	 constructors
constructors_standings	 driver_alpha	 driver_alpha_teammate	 driver_standings	 driver_summary	 drivers	 final_standings	 head_to_head	 lap_avg
lap_times	 leader_points	 master_driver	 merged	 pit_driver	 pit_stops	 pit_team	 qualified_drivers	 qualifying
qualifying_avg	 qualifying_drivers	 qualifying_merge	 race_position	 races	 results	 season_finals	 season_races	 second_driver
status	 team_drivers	 team_pits	 team_rankings	 team_totals	 teammate_compare	 teammate_counts	 teammate_data	 teammate_filtered
top_drivers	 top_teammates	 year_totals

In [166]:
master_driver.columns.tolist()

['driver_name',
 'Races',
 'Wins',
 'Podiums',
 'Total_Points',
 'Win_Rate',
 'Podium_Rate',
 'Opportunity_Score',
 'Seasons',
 'Avg_Outperformance',
 'Championship_Score',
 'Driver_Alpha_V1',
 'Championships',
 'Longevity_Score',
 'Driver_Alpha_V2',
 'Opportunity_Norm',
 'Outperformance_Norm',
 'Championship_Norm',
 'Longevity_Norm',
 'Driver_Alpha_V3',
 'Qualifying_Score',
 'Race_Pace_Score']

In [167]:
team_pits.columns.tolist()

['constructorRef',
 'Avg_Pit_Stop',
 'Total_Pit_Stops',
 'Operational_Efficiency_Score']

In [168]:
constructor_finals.columns.tolist()

['constructorStandingsId',
 'raceId',
 'constructorId',
 'points',
 'position',
 'positionText',
 'wins',
 'year',
 'constructorRef',
 'Season_Total_Points',
 'Points_Share',
 'Total_Races',
 'Win_Share',
 'Car_Dominance_Score',
 'Car_Dominance_V2']

In [169]:
master_driver.shape

(861, 22)

In [170]:
team_pits.shape

(23, 4)

In [171]:
constructor_finals.shape

(920, 15)

In [172]:
master_driver[
    [
        'driver_name',
        'Driver_Alpha_V3',
        'Qualifying_Score',
        'Race_Pace_Score'
    ]
].head()

     driver_name  Driver_Alpha_V3  Qualifying_Score  Race_Pace_Score
0   Adolf Brudes         0.000371               NaN              NaN
1    Adolfo Cruz         0.000371               NaN              NaN
2   Adrian Sutil         0.064860          0.067368         0.076683
3  Adrián Campos         0.007797               NaN              NaN
4   Aguri Suzuki         0.035060          0.061404              NaN

In [173]:
for df in [
    'master_driver',
    'qualifying_avg',
    'race_position',
    'lap_avg',
    'team_pits',
    'constructor_finals',
    'teammate_compare'
]:
    try:
        print(df, eval(df).shape)
    except:
        print(df, "not found")

master_driver (861, 22)
qualifying_avg (172, 4)
race_position (143, 5)
lap_avg (143, 3)
team_pits (23, 4)
constructor_finals (920, 15)
teammate_compare (599, 11)

In [174]:
qualifying_avg.to_csv(
    "qualifying_avg.csv",
    index=False
)

race_position.to_csv(
    "race_position.csv",
    index=False
)

lap_avg.to_csv(
    "lap_avg.csv",
    index=False
)

teammate_compare.to_csv(
    "teammate_compare.csv",
    index=False
)